### ISSUE TITLE
tv_grab_pt_meo no longer works

### ISSUE THREAD

**Issue by paulopais** [XMLTV/xmltv#100]
XMLTV Version?
0.6.1

XMLTV Component?
tv_grab_pt_*** version 0.6.1

What happened?
Failed to fetch channels .

What did you expect to happen?
Fetch epg .

Did you see any warnings/errors?
2020-06-20 14:45:41.154 xmltv: /usr/bin/tv_grab_pt_meo: no output detected
2020-06-20 14:45:41.154 xmltv: /usr/bin/tv_grab_pt_meo: grab returned no data
or
2020-06-20 14:45:41.154 xmltv: /usr/bin/tv_grab_pt_vodafone: no output detected
2020-06-20 14:45:41.154 xmltv: /usr/bin/tv_grab_pt_vodafone: grab returned no data

What steps are needed to reproduce this issue?
run tv_grab_pt_vodafone after configuration

Any other information?
Stop working last month

What other software are you using?
Debian

**Comment by honir** [comment]
Looks like the EPG service from SAPO has closed down. Pages are returning a page not found error

http://services.sapo.pt/EPG/GetChannelListByDateInterval?channelSiglas=RTP1&startDate=2020-07-04
http://services.sapo.pt/Metadata/Service/EPG?culture=EN
https://store.services.sapo.pt/en/cat/catalog/other/meo-epg/technical-description

**Comment by knowledgejunkie** [comment]
@paulopais Please can you try the development version of tv_grab_pt_vodafone from git, as this grabber has recently been updated.

I've just tested it locally with channels:

channel=RTP 1 HD
channel=RTP 2
channel=SIC
channel=TVI HD

and it seemed to work as expected.

**Comment by knowledgejunkie** [comment]
I'll disable the pt_meo grabber and await confirmation that pt_vodafone is working for @paulopais

**Comment by knowledgejunkie** [comment]
tv_grab_pt_meo disabled in https://github.com/XMLTV/xmltv/commit/b8695581f05b16dd946fdee00bd50c05c1c7fca6

**Comment by xppx99** [comment]
Hi, 
I've tested and I can confirm that the pt_vodafone grabber is working very well. Thanks

**Comment by higuita** [comment]
I will try to contact Meo support and see if i can get more info about the service

In worst case, we may need to rebuild the meo grabber to use the web site:

https://www.meo.pt/tv/novidades-canais/guia-tv/canal

**Comment by knowledgejunkie** [comment]
@higuita Did you ever hear back from Meo support?

**Comment by honir** [comment]
It looks possible to build a grabber to use https://www.meo.pt/tv/canais-programacao/guia-tv

Before I take a look, please can someone confirm their Terms & Conditions (in Portuguese) do not prohibit this use.

**Comment by xppx99** [comment]
I've been trying to dig within the websit, but did not found any Terms & Conditions referred specifically to this "product", because in fact the information made available itself is not a product.  

The closest terms & conditions available are the ones referred to the online store, but even this I think it's very different. 

Having said this, I can only see two options: 
1. Someone can try to contact MEO and ask specifically for permission for this type of use. I'm afraid that we wont have a response soon, or a response at all... 
2. Developing this grabber and in the case that we get some complaint, remove it/disable it.

**Comment by honir** [comment]
I've updated a replacement for tv_grab_pt_meo.

Note you will need to regenerate your config-file  (i.e. run the `--configure` option)

**Comment by knowledgejunkie** [comment]
Thank you @honir

**Comment by diogopms** [comment]
Is this still working? i'm having some issues on getting the last EPG from Meo

**Comment by honir** [comment]
@diogopms Please open a new issue, completing the form with the requested information.
