### ISSUE TITLE
Use of uninitialized value $zip in string at /usr/local/bin/tv_grab_na_dtv line 316.

### ISSUE THREAD

**Issue by venkiheidi1975** [XMLTV/xmltv#103]
HI, 

I have downloaded xmltv from github then installed  on Ubuntu 16.04 as well as 18.04 server.  While executing below command

tv_grab_na_dtv --configure    (Given zip code Newyork 41017and selected timezone is 0 (America/Newyork)

got below information then stuck,  After that no progress.

Use of uninitialized value $zip in string at /usr/local/bin/tv_grab_na_dtv line 316

Can you help me to resolve this issue.

Perl version is 5.26.1
OS : Ubuntu 16.04 
xmltv version is 0.6.1

Rgds
Venkatesan K

**Comment by garybuhrmaster** [comment]
Commit 66b677fc changed the calling params for the getBrowser routine, but failed to update one of the callers.  Please try the following patch to verify it fixes your issue.


```
diff --git a/grab/na_dtv/tv_grab_na_dtv b/grab/na_dtv/tv_grab_na_dtv
index 3b327904..0adc76c8 100755
--- a/grab/na_dtv/tv_grab_na_dtv
+++ b/grab/na_dtv/tv_grab_na_dtv
@@ -555,7 +555,7 @@ sub list_channels {
 
   $VERBOSE = !$opt->{quiet};
 
-  my $browser = getBrowser($conf);
+  my $browser = getBrowser($opt, $conf);
   &scrape_channel_list( $browser, $conf->{zip}[0], $conf->{channel}, \%ch );
 
   my $xml = $XML_PRELUDE;
```
