### ISSUE TITLE
tv_grab_il: broken due to upstream site changes

### ISSUE THREAD

**Issue by knowledgejunkie** [XMLTV/xmltv#107]
XMLTV Version?
--------------

0.6.1

XMLTV Component?
----------------

tv_grab_il

What happened?
--------------

Does not configure, retrieve channels or programmes

What did you expect to happen?
------------------------------

Successful configuration and listings retrieval

Did you see any warnings/errors?
--------------------------------

Parsing result: (nothing to do)

What steps are needed to reproduce this issue?
----------------------------------------------

Attempt to reconfigure the grabber and/or retrieve channels using existing test.conf

Any other information?
----------------------

This is recent change. Upstream site layout/DOM changes responsible.

What other software are you using?
----------------------------------
**Operating System:** Debian bullseye/sid

**Perl Version:** 5.30.3

**Comment by honir** [comment]
Source website has changed significantly and no longer offers json content. Grabber needs to be changed to do old-school scraping.

**Comment by rmeden** [comment]
grabber has been removed from the distribution due to upstream changes
