### ISSUE TITLE
differing timezone between channels

### ISSUE THREAD

**Issue by joshinils** [XMLTV/xmltv#111]
XMLTV Version?
--------------
XMLTV module version 0.6.1
This is tv_grab_eu_xmltvse version 0.6.1

XMLTV Component?
----------------
This is tv_grab_eu_xmltvse version 0.6.1

What happened?
--------------
timestamps are differing in timezone between channels

What did you expect to happen?
------------------------------
every channel to be encoded with the same timezone

Did you see any warnings/errors?
--------------------------------
no

What steps are needed to reproduce this issue?
----------------------------------------------
`tv_grab_eu_xmltvse --config-file .xmltv/tv_grab_eu_xmltvse.conf --output tv.xml`
in the directory which is cloned from: https://github.com/joshinils/tv/
ie. using https://github.com/joshinils/tv/blob/master/.xmltv/tv_grab_eu_xmltvse.conf as the config file

hd.daserste.de is apparently in utc, whereas berl.rbb-online.de is in localtime utc+2 (summertime)
but the timestamp in the xml file is encoded with `start="20200907140000 +0000"` both have the same +0000.

Any other information?
----------------------
apparently today all info for hd.daserste.de is gone, great. soo i cant really test this.

What other software are you using?
----------------------------------
**Operating System:** NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

**Perl Version:** This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
(with 46 registered patches, see perl -V for more detail)

**Comment by joshinils** [comment]
hm, looks like half of the channels I chose are not working anymore.

- [ ] hd.daserste.de
- [x] hd.zdf.de
- [x] berl.rbb-online.de
- [ ] sachsen.mdr.daserste.de
- [ ] hr.daserste.de
- [ ] sat1.de
- [x] rtl.de
- [ ] prosieben.de
- [ ] ndrhd.daserste.de
- [ ] hd.3sat.de
- [ ] rp.swr.daserste.de
- [ ] wdrhd.daserste.de
- [ ] kabel1.de
- [x] vox.de
- [x] super.rtl.de
- [ ] hd.arte.de
- [ ] sixx.de
- [ ] nord.bfs.daserste.de
- [x] rtl2.de
- [x] infokanal.zdf.de
- [x] neohd.zdf.de
- [ ] phoenixhd.daserste.de
- [x] n-tv.de
- [ ] tele5.de

**Comment by garybuhrmaster** [comment]
The tv_grab_eu_xmltvse grabber (after some configuration setup) essentially just pulls the xmltv files directly from xmltv.se itself (which generates them using its own mechanisms).  If the schedule data is incorrect it is likely best to open tickets with the upstream (the xmltv.se site) who would likely need to correct any offset issues (and such fixes would also fix the scheduling data for other users of that upstream source).

**Comment by joshinils** [comment]
Right, I have [done so](https://github.com/pixelmonster-ou/xmltv.se/issues/51).

**Comment by honir** [comment]
Closing this issue as this is a fault in the upstream data provider and @joshinils has logged a ticket there.
