### ISSUE TITLE
vendorId

### ISSUE THREAD

**Issue by geetee24** [XMLTV/xmltv#112]
Does anyone know how to get a "vendorId" ?  And if so, is it free?  No info anywhere on this.

Thank you

**Comment by pmhahn** [comment]
Please clarify your request as the term `vendor id` is used nowhere. So we don't know what you would like to get. Best is a link to some document where that term is used.

**Comment by knowledgejunkie** [comment]
@geetee24 As suggested, please provide us with more information about "vendorId"

**Comment by honir** [comment]
(bump)
@geetee24 Please can you provide more information on what you are looking for?

**Comment by honir** [comment]
Closed - off topic.
