### ISSUE TITLE
Episode numbers gone?

### ISSUE THREAD

**Issue by erkswede** [XMLTV/xmltv#114]
XMLTV Version?
----------
0.6.1

XMLTV Component?
----------
tv_grab_eu_xmltvse

What happened?
----------
There is no data for episode (and season) numbers

What did you expect to happen?
----------
There should be data for episode (and season) numbers

Did you see any warnings/errors?
----------
No

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. tv_grab_eu_xmltvse --config-file <config file for sweden, all channels>
2. Observe the data collected. No data for episode numbers are present.

Any other information?
----------------------
I observed this issue inside Mythtv 0.29 when certain episodes didn't record as expected and other episodes was recorded over and over again. In mythtv it's possible to view all data for a recording or programguide listing by pressing "i". From 2020-09-23 there is no episode data displayed. Before 2020-09-23 there is episode data present. Nothing is changed in my system around that time.

Trying to resolve this I have installed xmltv 0.6.1 but that didn't help. Same behavior with xmltv 0.5.7 and tv_grab_se_swedb.

What other software are you using?
----------------------------------
Ubuntu 16.04.3 LTS 

perl --version
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 58 registered patches, see perl -V for more detail)

**Comment by garybuhrmaster** [comment]
As that grabber just pulls the (already generated) xmltv files from the upstream source, you likely need to open a ticket with the upstream.  Given that your report says all channels, it could be a data transformation error by the upstream, or perhaps it was an intentional change to push you towards the upstreams commercially licensed service.  In any case, you should probably open a ticket with xmltv.se, as the xmltv project itself has no control of the upstream data.

**Comment by garybuhrmaster** [comment]
On another list it was stated by someone that the upstream (xmltv.se) has intentionally limited the free feed to three days of basic information (channel/time/title & subtitle/description/category only?) and the more detailed information of a longer duration will only be available via the upstreams companion premium (priced) service offering.  For some uses, the basic guide data may be useful, but obviously for more advanced scheduling purposes (such as your use of MythTV) it is likely going to be inadequate.

The planned changes were apparently announced back in early May, but finally happened.  I suspect most existing users of the free service never saw the announcement as things had just continued to work (until recently).  It was stated that some of the reasons for the changes were documented by the upstream.

Perhaps the xmltv.se project will reconsider some of the changes, or someone will find an alternative free and unencumbered source of guide data and contribute a new grabber to this project (which would be a good thing to see happen, if possible), or perhaps a new (or updated) grabber for the premium feed will be contributed for those that want that data.  I will note that there is at least one other premium guide service provider, Schedules Direct, used by the tv_grab_zz_sdjson and tv_grab_zz_sdjson_sqlite grabbers, has stated that they have coverage for (at least some) European broadcasters, so there is also that possibility.

I am going to close this issue as being out of scope for **this** project.

**Comment by erkswede** [comment]
Thanks for that exhaustive explanation and my excuses for creating a ticket in the wrong project.

**Comment by garybuhrmaster** [comment]
> Thanks for that exhaustive explanation and my excuses for creating a ticket in the wrong project.

Apologies are not necessary.  When projects layer it is often unclear whom is responsible for what, and it is a natural and quite reasonable thing to open issues with the project one is directly using.  Sometimes all a project (such as this) can do is point to that other project.
