### ISSUE TITLE
tv_grab_eu_xmltvse Failed to fetch http://xmltv.xmltv.se/channels-Germany.xml.gz

### ISSUE THREAD

**Issue by stuckinger** [XMLTV/xmltv#115]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
0.6.1-1
0.6.3-1

XMLTV Component?
----------------
tv_grab_eu_xmltvse

What happened?
---------------
grab returned no data

What did you expect to happen?
------------------------------
grab returns channel-list

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
```
 tvheadend[2327]: xmltv: /usr/bin/tv_grab_eu_xmltvse: grab /usr/bin/tv_grab_eu_xmltvse
 tvheadend[2327]: spawn: Executing "/usr/bin/tv_grab_eu_xmltvse"
 tvheadend[2327]: spawn: Failed to fetch http://xmltv.xmltv.se/channels-Germany.xml.gz at /usr/bin/tv_grab_eu_xmltvse line 400.                                                                                                               
 tvheadend[2327]: xmltv: /usr/bin/tv_grab_eu_xmltvse: no output detected
 tvheadend[2327]: xmltv: /usr/bin/tv_grab_eu_xmltvse: grab returned no data
 tvheadend[2327]: xmltv: /usr/bin/tv_grab_eu_xmltvse: grab /usr/bin/tv_grab_eu_xmltvse
```

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. Use tvheadend to run interval grabbers
2. run /usr/bin/tv_grab_eu_xmltvse via cli

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
Fairly new, at most two weeks

What other software are you using?
----------------------------------
**Operating System:** Debian buster

**Perl Version:**  5.28.1-6+deb10u1 

Workaround
--------------
I realized the channels-File was available in my browser AND via wget, but curl said only '301 Moved Permanently' so I traced the actual location which is now https:// instead of http://

My Workaround was to edit  /usr/bin/tv_grab_eu_xmltvse to use https://
```
128: my $default_root_url = 'https://xmltv.xmltv.se/';
129: my $default_main_url = 'https://xmltv.se/';
```
Now it works again. I guess the perl script uses curl module to fetch and does not correctly follow the 301-message which directs to the new location?

**Comment by knowledgejunkie** [comment]
Thank you for your detailed bug report.

This issue was fixed in #116, so I'll close this bug.
