### ISSUE TITLE
XMLTV filtering: tv_grep, REGEX for channel-id

### ISSUE THREAD

**Issue by jobrien2001** [XMLTV/xmltv#12]
Under the current version it is only possible to REGEX filter the programming section by a command such as:
tv_grep --channel "^ch2.tv|^I3210" x1.xml

The output still leaves unfiltered channels (in the channel sections).

The only way to REGEX filter the channel section is by channel-name or EXACT match on channel-id.

Looks like implementing REGEX on channel-id would be simple since the functionality is already there but my perl skills as lacking.

**Comment by honir** [comment]
That's all deliberate behaviour.

If you want to exclude channels entirely from the output file then you should remove them from your config file.

**Comment by jobrien2001** [comment]
Ok, I understand. 

What about regex capability on channel-id?  Can this be added?

**Comment by honir** [comment]
There isn't a use case for that (i.e. justification for why it's necessary). If you want to exclude channels then remove them from the config file. 

To retrieve data and then promptly discard it is poor practice. You shouldn't be retrieving information for channels which you aren't going to use - this puts an unnecessary load on the source site.

**Comment by jobrien2001** [comment]
Hello,

  I understand i shouldn't be retrieving unnecessary information for myself, but some of us do not have any control in the source programming.

  I am trying to filter unneeded programming to I can deliver only relevant information to users.  I could easily hand users bigger files to users, but I'm not trying to be part of the problem.... I rather hand out only the relevant information that is light for their devices.

Having REGEX capability on channel-id would help me further cleanup an xml file.

**Comment by honir** [comment]
So you are sharing data with multiple users, but you are only an end-user yourself and acquiring the data from someone else? Be aware you are probably breaching the Terms of Use of the source site.

**Comment by honir** [comment]
I've added a new option --channel-id-exp to filter the xml by a regular expression on the channel "id" field. 

Channels and programmes which do not match the expression will be removed from the output.

e.g.  
```
tv_grep  --channel-id-exp  tcm  input.xml
tv_grep  --channel-id-exp  'e4|4music'  input.xml
```


.
(There were a couple of ways of implementing this - e.g. starting the string with ~ to denote a regexp - but I thought this was the best to avoid breaking existing functionality.)
