### ISSUE TITLE
tv_grab_pt_vodafone is broken

### ISSUE THREAD

**Issue by puf6** [XMLTV/xmltv#122]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
XMLTV module version 0.6.3

XMLTV Component?
----------------
tv_grab_pt_vodafone version 0.6.3

What happened?
--------------
tv_grab_pt_vodafone doesn't work again, probably due to API / website changes.

What did you expect to happen?
------------------------------
With an empty configuration file:

$ tv_grab_pt_vodafone --configure
 Error on the remote EPG API call
Select the channels that you want to receive data for.

With a pre-existing configuration file:

$ tv_grab_pt_vodafone 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

fetching data
requesting EPG from 2020-11-17 for RTP%201%20HD
 Error on the remote EPG API call
 Empty EPG download for RTP 1 HD, probably channel list is outdated or no API data for that channel
  Rerun the grabber configure to update the list or check for the channel EPG in the Vodafone app.
requesting EPG from 2020-11-17 for RTP%202
 Error on the remote EPG API call
 Empty EPG download for RTP 2, probably channel list is outdated or no API data for that channel
  Rerun the grabber configure to update the list or check for the channel EPG in the Vodafone app.

----------------------------------
**Operating System:** …

Linux 5.9.0
Perl v5.30.3

**Comment by xppx99** [comment]
I'm using the plugin fine, maybe it was a temporary problem from Vodafone?

**Comment by honir** [comment]
This seems to have been a transient problem with the source website. I have noticed intermittent timeouts when fetching the web data. The "solution" is to run it again and then it seems to work!

 I've run a test suite and it all works ok. Please re-open this issue if you are still getting problems.

**Comment by knowledgejunkie** [comment]
This grabber recently started failing again on my Debian unstable machine, despite the changes made in b74866fc, so I've investigated further.

The upstream server still uses weak Diffie-Hellman ciphers for key exchange. As a workaround we can specify that the script avoids using DH ciphers until this is fixed upstream.
