### ISSUE TITLE
tv_grab_na_dtv --debug outputs request logs to stdout

### ISSUE THREAD

**Issue by fugkco** [XMLTV/xmltv#124]
XMLTV Version?
--------------
v0.6.3

XMLTV Component?
----------------
tv_grab_na_dtv

What happened?
--------------
`--debug` flag outputs debug to `stdout` instead of of `stderr`

What did you expect to happen?
------------------------------
`--debug` flag should, as requested, show debugging output, but it should be output to `stderr` instead of `stdout`

Did you see any warnings/errors?
--------------------------------
N/A

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. tv_grab_na_dtv --configure
2. tv_grab_na_dtv --days 1 --debug > /tmp/tv.xml
3. notice tv.xml contains debug output - specifically requests and responses for all URLs retrieved.

Any other information?
----------------------
The reason this should be on stderr, is because, for example, when running this within TVHeadend, TVHeadend captures stdout, and sees stderr as log informations. Stdout doesn't contain valid xml if requests are output to stdout.

What other software are you using?
----------------------------------
TVHeadend

**Comment by honir** [comment]
Thanks for the report. Fixed in [library](https://github.com/XMLTV/xmltv/blob/master/grab/na_dtv/tv_grab_na_dtv)

Note: to reduce the extensive reporting from this grabber you could use the `--quiet` option in combination with `--debug`
