### ISSUE TITLE
tv_grab_eu_xmltvse not working

### ISSUE THREAD

**Issue by franckbonin** [XMLTV/xmltv#126]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
0.6.3

XMLTV Component?
----------------
tv_grab_eu_xmltvse

What happened?
--------------
Unable to configure grabber (a received URL seems not escaped ?)

What did you expect to happen?
------------------------------
Configure to happen

Did you see any warnings/errors?
--------------------------------
`/opt/local/bin/perl5.30 /opt/local/bin/tv_grab_eu_xmltvse --configure --debug`

:8: parser error : EntityRef: expecting ';'
s://fonts.googleapis.com/css2?family=Roboto:wght@200;300;400;500;700;900&display
                                                                                ^
:11: parser error : Specification mandates value for attribute defer
    <script defer type="text/javascript" src="/js/app-d348e9b7261d245151838642e8
                  ^
:11: parser error : attributes construct error
    <script defer type="text/javascript" src="/js/app-d348e9b7261d245151838642e8
                  ^
:11: parser error : Couldn't find end of Start Tag script line 11
    <script defer type="text/javascript" src="/js/app-d348e9b7261d245151838642e8
                  ^
:11: parser error : Opening and ending tag mismatch: link line 0 and script
ext/javascript" src="/js/app-d348e9b7261d245151838642e889d9ca.js?vsn=d"></script
                                                                                ^
:12: parser error : Opening and ending tag mismatch: meta line 0 and head
  </head>
         ^
:37: parser error : Specification mandates value for attribute x-cloak
        :class="{ 'fixed inset-0 z-10 flex items-center justify-center': show_mo
        ^
:37: parser error : attributes construct error
        :class="{ 'fixed inset-0 z-10 flex items-center justify-center': show_mo
        ^
:37: parser error : Couldn't find end of Start Tag div line 32
        :class="{ 'fixed inset-0 z-10 flex items-center justify-center': show_mo
        ^
:39: parser error : error parsing attribute name
12 md:max-w-xl mx-auto rounded-lg shadow-xl text-left mb-2" x-show="show_modal" 
                                                                                ^
:39: parser error : attributes construct error
12 md:max-w-xl mx-auto rounded-lg shadow-xl text-left mb-2" x-show="show_modal" 
                                                                                ^
:39: parser error : Couldn't find end of Start Tag div line 39
12 md:max-w-xl mx-auto rounded-lg shadow-xl text-left mb-2" x-show="show_modal" 
                                                                                ^
:46: parser error : xmlParseEntityRef: no name
            <template x-if="channels && channels.length">
                                      ^
:46: parser error : xmlParseEntityRef: no name
            <template x-if="channels && channels.length">
                                       ^
:50: namespace error : Failed to parse QName ':key'
                        <template x-for="channel in channels" :key="channel.id">
                                                                  ^
:54: namespace error : Failed to parse QName ':src'
                                        <img class="w-full" :src="channel.logo" 
                                                                ^
:58: namespace error : Failed to parse QName ':value'
                                <input type="checkbox" :value="channel.selected"
                                                             ^
:58: parser error : error parsing attribute name
                               <input type="checkbox" :value="channel.selected" 
                                                                                ^
:58: parser error : attributes construct error
                               <input type="checkbox" :value="channel.selected" 
                                                                                ^
:58: parser error : Couldn't find end of Start Tag input line 58
                               <input type="checkbox" :value="channel.selected" 
                                                                                ^
:62: parser error : Opening and ending tag mismatch: h2 line 0 and div
                </div>
                      ^
:63: parser error : Opening and ending tag mismatch: h2 line 0 and template
            </template>
                       ^
:68: parser error : error parsing attribute name
          <a class="absolute top-0 right-0 text-white mt-3 mr-3 cursor-pointer" 
                                                                                ^
:68: parser error : attributes construct error
          <a class="absolute top-0 right-0 text-white mt-3 mr-3 cursor-pointer" 
                                                                                ^
:68: parser error : Couldn't find end of Start Tag a line 68
          <a class="absolute top-0 right-0 text-white mt-3 mr-3 cursor-pointer" 
                                                                                ^
:70: parser error : Opening and ending tag mismatch: div line 0 and a
                        </a>
                            ^
:71: namespace error : Failed to parse QName ':src'
                        <img class="h-full w-full object-cover" :src="programme.
                                                                    ^
:73: namespace error : Failed to parse QName ':class'
-center text-sm font-medium leading-none tracking-wide py-1 px-2 rounded" :class
                                                                                ^
:76: namespace error : Failed to parse QName ':class'
-center text-sm font-medium leading-none tracking-wide py-1 px-2 rounded" :class
                                                                                ^
:79: namespace error : Failed to parse QName ':class'
-center text-sm font-medium leading-none tracking-wide py-1 px-2 rounded" :class
                                                                                ^
:83: namespace error : Failed to parse QName ':class'
                    <div :class="actualColor(actualColor('border-b px-4 py-3 rel
                               ^
:86: namespace error : Failed to parse QName ':src'
                                <img class="w-full z-40" :src="programme.channel
                                                             ^
:88: namespace error : Failed to parse QName ':class'
                            <div :class="actualColor('pl-4 text-sm flex-1 z-40',
                                       ^
:90: namespace error : Failed to parse QName ':href'
 class="font-semibold">Airing on <a class="font-black hover:text-gray-900" :href
                                                                                ^
:93: namespace error : Failed to parse QName ':style'
                        <div :style="percentageWidth(programme.percentage)" :cla
                                   ^
:93: namespace error : Failed to parse QName ':class'
                      <div :style="percentageWidth(programme.percentage)" :class
                                                                                ^
:115: namespace error : Failed to parse QName ':key'
                  <template x-for="country in programme.production_country" :key
                                                                                ^
:129: namespace error : Failed to parse QName ':key'
                              <template x-for="credit in programme.credits" :key
                                                                                ^
:132: namespace error : Failed to parse QName ':src'
                                    <img class="h-full w-full object-cover" :src
                                                                                ^
:144: parser error : Opening and ending tag mismatch: template line 0 and div
                </div>
                      ^
:145: parser error : Opening and ending tag mismatch: div line 0 and template
            </template>
                       ^
:146: parser error : Opening and ending tag mismatch: template line 0 and div
    </div>
          ^
:223: parser error : Entity 'copy' not defined
  <span class="flex-1">&copy; Pixelmonster - 2020</span>
                             ^
:242: parser error : Opening and ending tag mismatch: body line 0 and div
    </div>
          ^
:243: parser error : Opening and ending tag mismatch: meta line 0 and body
  </body>
         ^
:244: parser error : Opening and ending tag mismatch: meta line 0 and html
</html>
       ^
:245: parser error : EndTag: '</' not found`

What steps are needed to reproduce this issue?
----------------------------------------------
/opt/local/bin/perl5.30 /opt/local/bin/tv_grab_eu_xmltvse --configure --debug

Any other information?
----------------------
other grabber seems to work

What other software are you using?
----------------------------------
**Operating System:** MacOs 10.13

**Perl Version:** 5.30

**Comment by Phil1023** [comment]
Hi, I receive the same error message.

I installed xmltv on a raspberry pi (Raspberry Pi OS Light) via apt-get.

When I execute 
`tv_grab_eu_xmltvse --configure`
I get the following message:
```
:8: parser error : EntityRef: expecting ';'
s://fonts.googleapis.com/css2?family=Roboto:wght@200;300;400;500;700;900&display
                                                                                ^
:11: parser error : Specification mandate value for attribute defer
    <script defer type="text/javascript" src="/js/app-d348e9b7261d245151838642e8
                  ^
:11: parser error : attributes construct error
    <script defer type="text/javascript" src="/js/app-d348e9b7261d245151838642e8
                  ^
:11: parser error : Couldn't find end of Start Tag script line 11
    <script defer type="text/javascript" src="/js/app-d348e9b7261d245151838642e8
                  ^
:11: parser error : Opening and ending tag mismatch: link line 8 and script
ext/javascript" src="/js/app-d348e9b7261d245151838642e889d9ca.js?vsn=d"></script
                                                                                ^
:12: parser error : Opening and ending tag mismatch: meta line 7 and head
  </head>
         ^
:37: parser error : Specification mandate value for attribute x-cloak
        :class="{ 'fixed inset-0 z-10 flex items-center justify-center': show_mo
        ^
:37: parser error : attributes construct error
        :class="{ 'fixed inset-0 z-10 flex items-center justify-center': show_mo
        ^
:37: parser error : Couldn't find end of Start Tag div line 32
        :class="{ 'fixed inset-0 z-10 flex items-center justify-center': show_mo
        ^
:39: parser error : error parsing attribute name
12 md:max-w-xl mx-auto rounded-lg shadow-xl text-left mb-2" x-show="show_modal" 
                                                                                ^
:39: parser error : attributes construct error
12 md:max-w-xl mx-auto rounded-lg shadow-xl text-left mb-2" x-show="show_modal" 
                                                                                ^
:39: parser error : Couldn't find end of Start Tag div line 39
12 md:max-w-xl mx-auto rounded-lg shadow-xl text-left mb-2" x-show="show_modal" 
                                                                                ^
:46: parser error : xmlParseEntityRef: no name
            <template x-if="channels && channels.length">
                                      ^
:46: parser error : xmlParseEntityRef: no name
            <template x-if="channels && channels.length">
                                       ^
:50: namespace error : Failed to parse QName ':key'
                        <template x-for="channel in channels" :key="channel.id">
                                                                  ^
:54: namespace error : Failed to parse QName ':src'
                                        <img class="w-full" :src="channel.logo" 
                                                                ^
:58: namespace error : Failed to parse QName ':value'
                                <input type="checkbox" :value="channel.selected"
                                                             ^
:58: parser error : error parsing attribute name
                               <input type="checkbox" :value="channel.selected" 
                                                                                ^
:58: parser error : attributes construct error
                               <input type="checkbox" :value="channel.selected" 
                                                                                ^
:58: parser error : Couldn't find end of Start Tag input line 58
                               <input type="checkbox" :value="channel.selected" 
                                                                                ^
:62: parser error : Opening and ending tag mismatch: h2 line 48 and div
                </div>
                      ^
:63: parser error : Opening and ending tag mismatch: h2 line 48 and template
            </template>
                       ^
:68: parser error : error parsing attribute name
          <a class="absolute top-0 right-0 text-white mt-3 mr-3 cursor-pointer" 
                                                                                ^
:68: parser error : attributes construct error
          <a class="absolute top-0 right-0 text-white mt-3 mr-3 cursor-pointer" 
                                                                                ^
:68: parser error : Couldn't find end of Start Tag a line 68
          <a class="absolute top-0 right-0 text-white mt-3 mr-3 cursor-pointer" 
                                                                                ^
:70: parser error : Opening and ending tag mismatch: div line 67 and a
                        </a>
                            ^
:71: namespace error : Failed to parse QName ':src'
                        <img class="h-full w-full object-cover" :src="programme.
                                                                    ^
:73: namespace error : Failed to parse QName ':class'
-center text-sm font-medium leading-none tracking-wide py-1 px-2 rounded" :class
                                                                                ^
:76: namespace error : Failed to parse QName ':class'
-center text-sm font-medium leading-none tracking-wide py-1 px-2 rounded" :class
                                                                                ^
:79: namespace error : Failed to parse QName ':class'
-center text-sm font-medium leading-none tracking-wide py-1 px-2 rounded" :class
                                                                                ^
:83: namespace error : Failed to parse QName ':class'
                    <div :class="actualColor(actualColor('border-b px-4 py-3 rel
                               ^
:86: namespace error : Failed to parse QName ':src'
                                <img class="w-full z-40" :src="programme.channel
                                                             ^
:88: namespace error : Failed to parse QName ':class'
                            <div :class="actualColor('pl-4 text-sm flex-1 z-40',
                                       ^
:90: namespace error : Failed to parse QName ':href'
 class="font-semibold">Airing on <a class="font-black hover:text-gray-900" :href
                                                                                ^
:93: namespace error : Failed to parse QName ':style'
                        <div :style="percentageWidth(programme.percentage)" :cla
                                   ^
:93: namespace error : Failed to parse QName ':class'
                      <div :style="percentageWidth(programme.percentage)" :class
                                                                                ^
:115: namespace error : Failed to parse QName ':key'
                  <template x-for="country in programme.production_country" :key
                                                                                ^
:129: namespace error : Failed to parse QName ':key'
                              <template x-for="credit in programme.credits" :key
                                                                                ^
:132: namespace error : Failed to parse QName ':src'
                                    <img class="h-full w-full object-cover" :src
                                                                                ^
:144: parser error : Opening and ending tag mismatch: template line 65 and div
                </div>
                      ^
:145: parser error : Opening and ending tag mismatch: div line 47 and template
            </template>
                       ^
:146: parser error : Opening and ending tag mismatch: template line 46 and div
    </div>
          ^
:223: parser error : Entity 'copy' not defined
  <span class="flex-1">&copy; Pixelmonster - 2020</span>
                             ^
:242: parser error : Opening and ending tag mismatch: body line 13 and div
    </div>
          ^
:243: parser error : Opening and ending tag mismatch: meta line 5 and body
  </body>
         ^
:244: parser error : Opening and ending tag mismatch: meta line 5 and html
</html>
       ^
:245: parser error : Premature end of data in tag meta line 4

^
:245: parser error : Premature end of data in tag head line 3

^
:245: parser error : Premature end of data in tag html line 2

^

```
### XMLTV Version?
xmltv (0.6.1-1) unstable

### XMLTV Component?
tv_grab_eu_xmltvse

### What other software are you using?
perl (5.28.1-6) unstable
Raspbian GNU/Linux 10 (buster)

**Comment by jnylen** [comment]
@franckbonin 
This should now be up and working, can you confirm on your side?

**Comment by knowledgejunkie** [comment]
Mentioned this to @jnylen on IRC a few moments ago, came here to update the thread, and he's already assigned it to himself and pushed a fix to the data source!

**Comment by knowledgejunkie** [comment]
Successfully tested locally, so will remove the broken tag. I've also pushed an update to the grabber's test.conf

Will wait for @franckbonin to respond before closing this.

**Comment by franckbonin** [comment]
It works, confirmed !
