### ISSUE TITLE
Windows version updated to 0.6.1?

### ISSUE THREAD

**Issue by garybuhrmaster** [XMLTV/xmltv#129]
FD: Untested/unverified as I don't run Windows, only observed when reviewing recent patches.

In commit 1747b204af78a0ed1672525a9b277ad1b2f9b906 (update windows xmltv.exe to use PAR::Packer rather than discontinued PerlApp) there is an update fragment that changes $VERSION from 0.6.3 to 0.6.1:

```
@@ -68,7 +75,7 @@ print STDERR "Timezone is $ENV{TZ}\n" unless $opt_quiet;
 $cmd = shift || "";
 
 # --version (and abbreviations thereof)
-my $VERSION = '0.6.3';
+my $VERSION = '0.6.1';
 if (index('--version', $cmd) == 0 and length $cmd >= 3) {
     print "xmltv $VERSION\n";
     exit;
```

This seems to me to be wrong as the current version is 0.6.3.  Either that or I am misunderstanding the intention.

**Comment by honir** [comment]
I think you're right.

@rmeden Should this be 0.6.3 ?

**Comment by rmeden** [comment]
It's been a decade since I wrote the exe_wrap.pl script (now xmltv.pl), 
but I had to hard-code the version number because it didn't "use 
XMLTV;".   (because it didn't need any XMLTV modules)

The new script added it, so it now gets the version from XMLTV.pm and 
there is no hard-coded version.
