### ISSUE TITLE
--days more than 3 not working?

### ISSUE THREAD

**Issue by TomasHektor** [XMLTV/xmltv#130]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
0.6.3 (also tried 0.5.70)

XMLTV Component?
----------------
tv_grab_eu_xmltvse (also tried tv_grab_se_tvzon for 0.5.70)

What happened?
--------------
--days 1, 2 and 3 work as expected, whenever a number >3 is entered, only 3 days of data is grabbed.

What did you expect to happen?
------------------------------
…

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
No warnings or errors

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. (in .bat-file) c:\PATH_TO_XMLTV\xmltv-0.6.3\xmltv.exe tv_grab_eu_xmltvse --days 14 > "c:\PATH_TO_XML_FILE\tv-guide.xml" %*

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
Not sure but think it has been present for a couple of weeks (saw it first on 0.5.70, upgraded to 0.6.3 but issue remains.)

What other software are you using?
----------------------------------
**Operating System:** Windows

**Perl Version:** Using the precompiled windows version.

**Comment by TomasHektor** [comment]
Update: omitting the --days option (which should default to 5?) still only gets 3 days of data.

**Comment by garybuhrmaster** [comment]
The upstream source of data for tv_grab_eu_xmltvse has decided to limit the duration, and detail, of the data provided from their free to use feed (they have a commercial feed with longer duration and more guide details and that paid service is referenced on their main project page).  The announcement from the upstream source about the changes can be read at: https://github.com/pixelmonster-ou/xmltv.se/issues/21 

Also related and discussed in: https://github.com/XMLTV/xmltv/issues/114

**Comment by TomasHektor** [comment]
Thank you for the explanation! Did not get the announcement that there should come a limit on the free feed. Sorry for posting an issue here.
