### ISSUE TITLE
tv_grab_ch_search: end times of "servus.search.ch" are wrong

### ISSUE THREAD

**Issue by angelaschmid** [XMLTV/xmltv#133]
XMLTV Version?
--------------
master

XMLTV Component?
----------------
tv_grab_ch_search

What happened?
--------------
All end times of "servus.search.ch" are wrong, they have times ending in seconds. It seems only to happen with "servus.search.ch".
Noticed also, when the seconds are "00", the start and end time are the same.
Daily updates make it impossible for Mythtv to add/delete/change/shift programs correctly.

What did you expect to happen?
------------------------------
correct end times.

Did you see any warnings/errors?
--------------------------------
grep "servus.search.ch" -A+2 <xml-file>
```
  <programme start="20210309130500 +0100" stop="202103091353**15** +0100" channel="servus.search.ch">
    <title lang="de">Die Highlands - Schottlands wildes Herz</title>
    <sub-title lang="de">Frühling (1/4)</sub-title>
--
  <programme start="**20210309140000** +0100" stop="**20210309140000** +0100" channel="servus.search.ch">
    <title lang="de">Auf legendären Routen</title>
    <sub-title lang="de">Südafrika</sub-title>
```
The ** are there just for quickly seeing the problems.

What steps are needed to reproduce this issue?
----------------------------------------------
grep "stop=\".............[1-9]" <xml-file>
Will show all end times which end in seconds.

Any other information?
----------------------

What other software are you using?
----------------------------------
Ubuntu
perl 5, version 26

**Comment by garybuhrmaster** [comment]
A quick look shows that the source site is providing the end times.  The xmltv grabber is simply grabbing the data and passing the values as specified along (while unusual, there is nothing technically wrong with shows starting/ending on any particular second).  You should likely contact the source site to inquire about why the times are what they are.

**Comment by FritzHerbers** [comment]
@garybuhrmaster
I looked at the online tv guide, there all seems OK. Do you please have a url (as used by the grabber) showing the incorrect dates.

**Comment by garybuhrmaster** [comment]
> @garybuhrmaster
> I looked at the online tv guide, there all seems OK. Do you please have a url (as used by the grabber) showing the incorrect dates.

The online guide hides some details from viewing.  Open one of the shows which have the info you do not like, and export the calendar file which shows the start/end times.  That file will contain the data.  Alternatively you can also do browser inspection of that link which shows the start/end, which is what the xmltv grabber does (it just parses the HTML)).

**Comment by FritzHerbers** [comment]
@garybuhrmaster 

What I couldn't figure out yesterday was, what the grabber is grabbing, is it the ics file href containing the times?

Today I also notice errors in the guide, e.g. the 14:00 show has the same start/end time:

![20210308_tvsearchtv-1](https://user-images.githubusercontent.com/10029682/110392506-51f71200-8069-11eb-9067-912184a4e7c3.PNG)

I will report to tv.search.ch tomorrow.

Thanks for your help.

**Comment by garybuhrmaster** [comment]
> What I couldn't figure out yesterday was, what the grabber is grabbing, is it the ics file href containing the times?

The XMLTV grabber script parses the href (there are start/end values there), but the ICS file itself is a bit more human readable for most.

> I will report to tv.search.ch tomorrow.

Good luck.

I would not be surprised to learn that tv.search.ch is getting the questionable data from their upstream, so they may need to report it up the line too (which may take time to get resolved).

**Comment by bhaak** [comment]
The parser is extracting the times from the link to the ics file. It's not parsing the ics file itself.

But if you look at ics file, you see that the end time is with seconds as well, for example here: https://tv.search.ch/servus/2021-03-13T20:15:00-miss-fishers-mysterioese-mordfaelle

What's even worse though is that the whole page on search.ch is off by one day. Look at the previous entry. It's from yesterday, a friday, but search.ch claims it's being broadcasted today. https://www.servustv.com/tv-programm/?date=2021-03-12#night

So tv_grab_ch_search is just reporting what it gets from search.ch. There's something wrong at their end.

**Comment by FritzHerbers** [comment]
I sent a mail to 'customercare@localsearch.ch' on 2021-03-09, but haven't heard back. I think this mail address is more for the telephone book services.
Do you have another contact?

**Comment by bhaak** [comment]
There's a generic contact form on the site https://www.search.ch/contact?s=tv but I don't know if this results in a faster response.

**Comment by FritzHerbers** [comment]
I contacted 'customercare@localsearch.ch' several times. The problem seems to be resolved.

**Comment by garybuhrmaster** [comment]
Thanks for the followup.  Since this was an upstream issue, and has now been resolved, I am going to close the issue.
