### ISSUE TITLE
[xmltv.dtd] Missing description for icon in channel element

### ISSUE THREAD

**Issue by cocool97** [XMLTV/xmltv#139]
I'm currently working on a Rust crate to generate XMLTV TV listing files. ([Available here](https://github.com/cocool97/xmltv-rs))

To conform to the XMLTV specification, I'm using a lot the DTD available in your repository.

I've found that the `icon` field in the `channel` element misses a description, which can lead to bad interpretations... I'll link a PR to this issue to suggest a consistent description.

- XMLTV Version? 1.0.0 -> `master` branch

- What happened? Missing description field for `icon` attribute of `channel`

**Comment by honir** [comment]
The 'icon' element is defined at line 329

```
<!-- An icon associated with the element that contains it.
src: uri of image
width, height: (optional) dimensions of image

These dimensions are pixel dimensions for the time being, eventually
this will change to be more like HTML's 'img'.
-->
<!ELEMENT icon EMPTY>
<!ATTLIST icon src         CDATA #REQUIRED
               width       CDATA #IMPLIED
               height      CDATA #IMPLIED

```

'icon' can be used by both 'channel' and 'programme'
