### ISSUE TITLE
 [xmltv.dtd] Url element not documented in programme element

### ISSUE THREAD

**Issue by cocool97** [XMLTV/xmltv#141]
I'm currently working on a Rust crate to generate XMLTV TV listing files. (Available here)

To conform to the XMLTV specification, I'm using a lot the DTD available in your repository.

I've found that the url field of the `programme` element is not documented in the xmltv.dtd file. What is the correct way to understand it ?

Same thing, a `value` field is documented but not very understandable... Should this field be changed for `url` instead ?

    XMLTV Version? 1.0.0 -> master branch

    What happened? Weird field `url` in xmltv.dtd file

**Comment by honir** [comment]
'url' is there but perhaps not easy to find:

```
<!-- A URL where you can find out more about the element that contains
it (programme or channel).  This might be the official site, or a fan
page, whatever you like really.

If multiple url elements are given, the most authoritative or official
(which might conflict...) sites should be listed first.
-->
<!ELEMENT url (#PCDATA)>
```

The exact value of the url may vary according to the source site for the schedule.


'value' is used by 'rating' and 'star-rating' elements. See the example at the top of the DTD.

The content of 'value' will vary depending on the container. e.g. for 'rating' it might be 'PG', '18', or whatever the classification system determined; for star-rating it might be '3/3', '4.7', or whatever the source site sets.
