### ISSUE TITLE
tv_grab_fr outputs multiple errors when running

### ISSUE THREAD

**Issue by kalon33** [XMLTV/xmltv#144]
XMLTV Version?
1.0.0

XMLTV Component?
----------------
tv_grab_fr

What happened?
----------------
Launching latest tv_grab_fr under Ubuntu 18.04LTS, I got these errors:
   
```
tv_grab_fr > /var/www/ratp/epg.xml
Use of uninitialized value $c_id in exists at /usr/bin/tv_grab_fr line 294.
Use of uninitialized value $c_id in concatenation (.) or string at /usr/bin/tv_grab_fr line 295.
Getting listings...: ##################################################
Use of uninitialized value $date_string in pattern match (m//) at /usr/bin/tv_grab_fr line 799.
Validation failed for type named DayOfMonth declared in package DateTime::Types (/usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime/Types.pm
) at line 29 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named DayOfMonth declared in package DateTime::Typ
es (/usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime/Types.pm) at line 29 in sub named (eval) with value undef', 'type', 'Specio::Constrai
nt::Simple=HASH(0x564277ed3e38)', 'value', undef) called at (eval 224) line 91
DateTime::_check_new_params('year', undef, 'month', undef, 'day', undef, 'hour', undef, 'minute', undef, 'second', undef, 'time_zone',
'Europe/Paris') called at /usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime.pm line 176
DateTime::new('DateTime', 'year', undef, 'month', undef, 'day', undef, 'hour', undef, 'minute', undef, 'second', undef, 'time_zone', 'E
urope/Paris') called at /usr/bin/tv_grab_fr line 800
main::get_datetime_from_xmltv_time(undef) called at /usr/bin/tv_grab_fr line 744
main::update_programme_stop_times('ARRAY(0x56427a0593f8)') called at /usr/bin/tv_grab_fr line 360
main::write_listings_data('XMLTV::Writer=HASH(0x564279494c28)', 'HASH(0x5642785ea460)') called at /usr/bin/tv_grab_fr line 77
```

**Comment by honir** [comment]
Looks like you need to update the channels in your conf file.

Run 
`tv_grab_fr --debug --days 1 --output /var/www/ratp/epg.xml`

and check for any clues

**Comment by honir** [comment]
@kalon33 did you resolve your problem? If so, please can you close this issue.

**Comment by honir** [comment]
Grabber passes validation tests.

**Comment by pimzand** [comment]
I'm seeing the same for any --days greater than 1

**Comment by honir** [comment]
@pimzand Please upgrade to version 1.1.2 of XMLTV and, if the issue still occurs, open a new issue providing the details requested in the issue template, as well as on which bouquet and channel the problem occurs.

**Comment by pimzand** [comment]
I'm using xmltv from rpmfusion for Fedora 35.
For now, I'm being lazy and have requested an update in https://bugzilla.rpmfusion.org/show_bug.cgi?id=6282

**Comment by garybuhrmaster** [comment]
> I'm using xmltv from rpmfusion for Fedora 35. For now, I'm being lazy and have requested an update in https://bugzilla.rpmfusion.org/show_bug.cgi?id=6282

The package was built in rpmfusion a few hours after release, however, it takes some time for the entire rpmfusion process (compose and mirroring) to complete percolating and the package to be installable via the package manager.

You can get the package directly from rpmfusion koji if you wish to skip the waiting.

**Comment by pimzand** [comment]
Thanks to @garybuhrmaster for updating the rpmfusion package even before I requested it.
Thanks to @honir for pointing me to the new version that indeed fixes the issue I was seeing.
