### ISSUE TITLE
No programme information in any of the feeds at http://www.xmltv.co.uk/feeds

### ISSUE THREAD

**Issue by caluml** [XMLTV/xmltv#146]
I can't find any contact information on xmltv.co.uk, so I'm hoping that someone here has some contact with them, and can let them know.
The main page does have a link to this repo, so I'm hoping it's the same people.

There hasn't been any programme information in any of the feeds at http://www.xmltv.co.uk/feeds

Could this be restored?

**Comment by honir** [comment]
Nothing to do with xmltv.org I'm afraid.

**Comment by garybuhrmaster** [comment]
FWIW, some people on avsforum have concluded that xmltv.co.uk is basically a zombie (occasionally shows signs of life, but appears mostly dead).  As you say, there is zero contact information, so when, or even if, it might shows signs of life again are unknown.  You may need to choose an alternative source of xmltv data for your application.

**Comment by caluml** [comment]
I'm happy to report that the feeds are now populated again, which is great news.
It had no feeds for quite some time, so the fact that it has started working a few hours after me posting an issue can't just be a coincidence - either way, I'm happy.
