### ISSUE TITLE
tv_grab_uk_tvguide is incompatible with tv_imdb

### ISSUE THREAD

**Issue by qdacsvx** [XMLTV/xmltv#147]
XMLTV Version?
--------------
git head

XMLTV Component?
----------------
tv_grab_uk_tvguide

What happened?
--------------

Using tv_imdb on the output of tv_grab_uk_tvguide results in an error.

What did you expect to happen?
------------------------------
tv_imdb works normally on the output of tv_grab_uk_tvguide. tv_grab_uk_tvguide produces output that is compatible with tv_imdb. The title tags for films output from tv_grab_uk_tvguide often contain wrong suffixes like " (YYYY)" where YYYY is a year, or " ()". tv_imdb produces a spurious error when it encounters a wrong title.

Did you see any warnings/errors?
--------------------------------
corrupt imdb database - hit on "Foxcatcher (2014)"

What steps are needed to reproduce this issue?
----------------------------------------------
1. tv_grab_uk_tvguide --output guide.xml
2. tv_imdb --imdbdir /tmp/imdb guide.xml

Any other information?
----------------------
If I fix the wrong titles by removing (YYYY) and () from the title tags in guide.xml, tv_imdb runs without errors.

What other software are you using?
----------------------------------
Xubuntu
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

**Comment by honir** [comment]
Thanks for the report.

Fix applied to IMDB.pm

**Comment by qdacsvx** [comment]
This fixes using tv_imdb with tv_grab_uk_tvguide. Are there other grabbers with eccentric output which might trip up tv_imdb?

There could be a sample output for each grabber which tv_imdb could be tested on. The samples should be periodically updated to track grabber changes.
