### ISSUE TITLE
is tv_grab_eu_xmltvse broken?

### ISSUE THREAD

**Issue by kami83** [XMLTV/xmltv#150]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
xmltv 1.0.0.

XMLTV Component?
----------------
all

What happened?
--------------
cannot fetch files from xmltv.se

What did you expect to happen?
------------------------------
Getting new epgdata

Did you see any warnings/errors?
--------------------------------
Failed to fetch https://xmltv.xmltv.se/channels-Germany.xml.gz at /usr/local/bin/tv_grab_eu_xmltvse line 400.

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. Just make an Update

**Comment by garybuhrmaster** [comment]
The tv_grab_eu_xmltvse grabber mostly just downloaded the data directly from the xmltv.se site.  At one time, issues with their data feed were to be reported in their github repository, but I note that that has been archived and made read-only, and most of the web references to xmltv.se that do still resolve now redirect to their commercial site, and there was a comment from the developer about potentially shutting down the free service in one of the archived github issues about the data feed ".... but that depends on if I decide if I should keep doing the free variant of xmltv.se or not as it's not paying for my time".  It is possible that the free service has been shutdown.

Perhaps you should ask about the status of the free data via their support email mailto:support@honeybee.it and if you get anything definitive, do reply here.

**Comment by iHaveAstream** [comment]
Hi,
have exactly the same issue since yesterday or the day before yesterday. Before that date (on 12/5) it used to work.

**Comment by wuppiwuppi** [comment]
Same issue I believe?
https://github.com/XMLTV/xmltv/issues/152
Any update? Is the free service shut down?

**Comment by jnylen** [comment]
@wuppiwuppi yes, the free service is closed down for now. It might pop up later if I have the time to maintain that part.

But the time and cost to maintain the free service are what I can't support it with right now. I'm also considering open-sourcing the Vind project that handled all the imports and exports for that part for anyone to start their own variant.

I'm closing this here, @honir feel free to remove that source in a future version. If it pops back up it won't have the same structure as it has now so the tool will not work regardless.

**Comment by honir** [comment]
Thanks @jnylen for the update - it's much appreciated.
