### ISSUE TITLE
tv_grab_de: command not found

### ISSUE THREAD

**Issue by JPVenson** [XMLTV/xmltv#162]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
0.6.1-1

XMLTV Component?
----------------
tv_grab_de

What happened?
--------------
Used:
`sudo apt-get install xmltv`
to obtain xmltv and run:
`tv_grab_de --configure`
but got
`tv_grab_de: command not found`

What did you expect to happen?
------------------------------
Configuration to be started

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
`tv_grab_de: command not found`

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. see above
2. …
3. …

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
…

What other software are you using?
----------------------------------
**Operating System:** WSL Ubuntu Linux 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
**Perl Version:** …

**Comment by honir** [comment]
Sorry but `tv_grab_de` has been broken for a long time. 

So it's not included when XMLTV is installed (hence 'command not found'). (The source code is left on here for reference)

**Comment by JPVenson** [comment]
I see thanks.
That should maybe for future reference be mentioned in the QuickStart guide?

**Comment by honir** [comment]
Good point. I've updated the QuickStart. Thanks
