### ISSUE TITLE
tv_grab_uk_tvguide list-channels

### ISSUE THREAD

**Issue by dizygotheca** [XMLTV/xmltv#163]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
1.1.0

XMLTV Component?
----------------
tv_grab_uk_tvguide

What happened?
--------------
channel_id from --list-channels does not match channel_id in guide data

What did you expect to happen?
------------------------------
channel_id should be consistent.
Many users (ie MythTV) derive (and store) an 'XMLTV id' verbatim from --list-channels and matching/wrangling the channel name once-in-a-blue-moon. This externally stored id is then used to interpret daily guide downloads.
Inconsistent channel_id's will break guide downloads for many users.

Did you see any warnings/errors?
--------------------------------
No

What steps are needed to reproduce this issue?
----------------------------------------------
$ tv_grab_uk_tvguide --list-channels
```
...
<channel id="363   # RT<C9>2">
    <display-name lang="en">RTÉ2</display-name>
    <icon src="https://cdn.tvguide.co.uk/channel_logos/60x35/363.png" />
    <url>https://www.tvguide.co.uk/mobile/channellisting.asp?ch=363</url>
</channel>
...
```
Note non-utf encoded name is not parsable by perl scripts using this output.

$ tv_grab_uk_tvguide --nodetailspage --days 1
```
...
<channel id="363.tvguide.co.uk">
    <display-name lang="en">RTÉ2</display-name>
</channel>
...
```
Any other information?
----------------------
1. Name in channel_id must be utf-encoded 
2. Addition of name in --list-channels channel_id requires user scripts to be modified to remove it.
3. --list-channels id is not RFC2838 compliant (which is now default option)

Huge thanks for the alternative channel fetching update. Works well!

What other software are you using?
----------------------------------
Linux
Perl 5.30.0

**Comment by honir** [comment]
Thanks for the report. That was my fault, sorry :-(

I've committed a fixed version - please can you give it a try?

https://github.com/XMLTV/xmltv/blob/master/grab/uk_tvguide/tv_grab_uk_tvguide

**Comment by mansoorhaq** [comment]
I guess for Windows users need to wait for the exe.

**Comment by rmeden** [comment]
On 2/18/2022 4:45 PM, Mansoor Haq wrote:
>
> I guess for Windows users need to wait for the exe.
>
I just updated the alpha-exe http://alpha-exe.xmltv.org

**Comment by dizygotheca** [comment]
Confirmed fix.
Thanks for all you do, honir.

**Comment by knowledgejunkie** [comment]
@honir Do you feel this issue warrants a patch release?

**Comment by honir** [comment]
@knowledgejunkie I think perhaps it does. It's reasonably 'broken' otherwise.
