### ISSUE TITLE
tv_grab_uk_tvguide failing to configure

### ISSUE THREAD

**Issue by mansoorhaq** [XMLTV/xmltv#165]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
1.1.1

XMLTV Component?
----------------
tv_grab_uk_tvguide

What happened?
--------------
Try to run tv_grab_uk_tvguide with --configure option which is the very first step... but getting the error as mentioned below.
I can not proceed without a proper config file, where I can enable or disable the channels.

What did you expect to happen?
------------------------------
Should be producing the .conf file

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
Can't call method "look_down" on an undefined value at /usr/bin/tv_grab_uk_tvguide line 758.

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
$ tv_grab_uk_tvguide --configure
tv_grab_uk_tvguide uses a cache with files that it has already downloaded. Please specify where the cache shall be stored.
Directory to store the cache in: [/home/user1/.xmltv/cache]
Fetching channels:   0% [                                                      ]     
Can't call method "look_down" on an undefined value at /usr/bin/tv_grab_uk_tvguide line 758.

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
Happens all the time.

What other software are you using?
----------------------------------
**Operating System:** …
Ubuntu 20.04.3 LTS

**Perl Version:** …
v5.30.0

**Comment by mkbloke** [comment]
Are you sure you're using the `tv_grab_uk_tvguide` grabber from version 1.1.1?  The error and line number do not seem to correspond with version 1.1.1.

**Comment by honir** [comment]
@mansoorhaq What is the output from  `tv_grab_uk_tvguide  --version`

**Comment by honir** [comment]
Closed - invalid.  Please update your software to version 1.1.1
