### ISSUE TITLE
Is there a complete list of supported tags anywhere?

### ISSUE THREAD

**Issue by Chris230291** [XMLTV/xmltv#167]
As the title suggests I am looking for a complete list of tags. I realise not all front ends will support all of the tags, but I would like to build my grabbers to the complete xmltv standard where possible.

Thanks,
Chris

**Comment by garybuhrmaster** [comment]
The xmltv.dtd file (in repository root directory) contains the definition of the supported tags/values.

**Comment by Chris230291** [comment]
Thanks
