### ISSUE TITLE
Update Windows perl build documentation

### ISSUE THREAD

**Issue by pmhahn** [XMLTV/xmltv#168]
On 3/7/2022 1:50 AM, witesbk wrote:
>
> @rmeden <https://github.com/rmeden> Yes, I've used these instructions. 
> But I found a few tripping hazards in it:
>
>  1. In http://wiki.xmltv.org/index.php/XMLTVWindowsBuild <url> it says
>     that one could use version xmltv-0.5.65.tar.bz2 for example. But
>     the makefile does not use PAR::Packer as stated here:
>     http://wiki.xmltv.org/index.php/XMLTVexeBuild <url>. With version
>     1.1.1 of the source code I works.
>  2. Quite a few directory names in the makefile have to be changed (at
>     least for the windows build), for example:
>     $(DESTDIR)/./$(PREFIX)/share/doc/xmltv-1.1.1 ->
>     $(DESTDIR)$(PREFIX)/share/doc/xmltv-1.1.1.
>     $(DESTDIR) is empty so the directories start with "/./" what makes
>     them invalid.
>  3. The packer module is "PAR::Packer" not "Par::Packer". So it has to
>     be installed with "cpan PAR::Packer".
>  4. "gmake xmltv.exe" also requires Params::Validate which has to be
>     installed by "cpan Params::Validate".
>
Par::Packer shouldn't be needed for "XMLTVWindowsBuild" only the EXE 
build.  (just don't do a "gmake xmltv.exe"  "gmake install" should 
install all the grabbers in native perl.

I didn't need to make any file changes, but my directories don't have 
spaces or version numbers in them ( C:\xmltv )

I haven't tried it from a tar distribution, just from a git pull... I'll 
have a new work laptop, I'll try to follow the instructions there and 
see if it needs updating.

Robert

_Originally posted by @rmeden in https://github.com/XMLTV/xmltv/issues/164#issuecomment-1061372356_

**Comment by rmeden** [comment]
I just ran thought the install and  made a few teaks. 

- updated the instructions to pull from github, not sourceforge (the instructions said that .tar.gz file was an example, not current)
- I didn't have a problem putting the zip file contents in c:\xmltv as I suggested (not xmltv-1.1.0)
- I updated the PAR::Packer name to be correct. 
- My install didn't need Params::Validate.  It was probably added by a WindowsBUild prerequsite.  I'll add it to the notes.
