### ISSUE TITLE
tv_grab_uk_tvguide timezone error during grabbing

### ISSUE THREAD

**Issue by qdacsvx** [XMLTV/xmltv#170]
XMLTV Version?
--------------
Git
XMLTV module version 1.1.1
tv_grab_uk_tvguide version 1.1.1

XMLTV Component?
----------------
tv_grab_uk_tvguide

What happened?
--------------
Error halts grabbing.

What did you expect to happen?
------------------------------
Grabbing runs without error.

Did you see any warnings/errors?
--------------------------------
 

> $tv_grab_uk_tvguide --days 1 --nodetailspage --debug
> ...
> Fetching https://www.tvguide.co.uk/channellistings.asp?ch=129&cTime=03%2F26%2F2022%2000%3A00%3A00 from server.
> Fetching https://www.tvguide.co.uk/channellistings.asp?ch=129&cTime=03%2F27%2F2022%2000%3A00%3A00 from server.
> Invalid local time for date in time zone: Europe/London
> 

What steps are needed to reproduce this issue?
----------------------------------------------

Run a configured grabber. Multiple channels produce this error.

Any other information?
----------------------
(For example, is this a new or intermittent issue?)

One or two channels failed yesterday. More today. Consistent failure.

What other software are you using?
----------------------------------
**Operating System:** … Xubuntu

**Perl Version:** … Perl 5 version 30

**Comment by honir** [comment]
Thanks for the report. Fixed in Git
