### ISSUE TITLE
Error with date in fr "TNT" configuration

### ISSUE THREAD

**Issue by Media38** [XMLTV/xmltv#174]
XMLTV Version?
1.1.1 

XMLTV Component?
xmltv.exe tv_grab_fr  --output TVguideTNT.xml

What happened?
An error appears with configuration "TNT" or "CANALSAT". It's OK with "BE Belgique" 👍 

Did you see any warnings/errors?
Getting listings...: ##################################################
Use of uninitialized value $date_string in pattern match (m//) at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc/script/tv_grab_fr line 799.
Validation failed for type named DayOfMonth declared in package DateTime::Types (C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\lib/DateTime/Types.pm) at line 29 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named DayOfMonth declared in package DateTime::Types (C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\lib/DateTime/Types.pm) at line 29 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x63d25e0)', 'value', undef) called at (eval 223) line 91
DateTime::_check_new_params('year', undef, 'month', undef, 'day', undef, 'hour', undef, 'minute', undef, 'second', undef, 'time_zone', 'Europe/Paris') called at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\lib\DateTime.pm line 176
DateTime::new('DateTime', 'year', undef, 'month', undef, 'day', undef, 'hour', undef, 'minute', undef, 'second', undef, 'time_zone', 'Europe/Paris') called at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\script\tv_grab_fr line 800
main::get_datetime_from_xmltv_time(undef) called at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\script\tv_grab_fr line 744
main::update_programme_stop_times('ARRAY(0x85ef230)') called at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\script\tv_grab_fr line 360
main::write_listings_data('XMLTV::Writer=HASH(0x7e2b870)', 'HASH(0x77f1448)') called at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\script\tv_grab_fr line 77
require script/tv_grab_fr at script\xmltv.pl line 136
require main at <embedded>\PAR.pm line 647
PAR::_run_member('Archive::Zip::ZipFileMember=HASH(0x4201fd0)', 1) called at script\main.pl line 46
require main at <embedded>\PAR.pm line 647
PAR::_run_member('Archive::Zip::ZipFileMember=HASH(0x41aa298)') called at <embedded>\PAR.pm line 434
PAR::import('PAR') called at -e line 594
eval {...} at -e line 42
__par_pl::BEGIN at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\script\tv_grab_fr line 0
eval {...} at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc\script\tv_grab_fr line 0
Windows 10

**Perl Version:** …

**Comment by honir** [comment]
Please try this new version.

Replace your existing file

C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc/script/tv_grab_fr

with [this new one](https://github.com/XMLTV/xmltv/raw/master/grab/fr/tv_grab_fr) (right-click and "save link as...").

There may be some missing programmes on Chasse et Pêche as they are missing the name of the programme and so are excluded from the xml.

Please let me know how it goes.

**Comment by Media38** [comment]
It's OK with this new version.
Thank you for all, it's simply perect.

**Comment by Media38** [comment]
Sorry for the fault : you must read "perfect" in place of "perect".
I close with total success.

**Comment by Slim1399** [comment]
I copied the script and pasted in the file==>The same message, no change
So i downloaded the file, I changed the permissions: always the same message !
