### ISSUE TITLE
tv_grab_fr : Can't call method "look_down"

### ISSUE THREAD

**Issue by Media38** [XMLTV/xmltv#176]
XMLTV Version?
1.1.1

XMLTV Component?
tv_grab_fr

What happened?
C:\Datas\XMLTv>xmltv.exe tv_grab_fr --config-file c:\datas\XMLTv\tv_grab_fr_Free.conf --output c:\datas\XMLTv\TVguideFREE.xml
Timezone is +0200
Getting listings...: ##############Can't call method "look_down" on an undefined value at C:\Users\dufou\AppData\Local\Temp\par-6475666f75\cache-0403651db53b5d86433fa2980270b3bd52f1e717\inc/script/tv_grab_fr line 425.

I add these lines 
    if (not defined $grid) {
        return;
    }
after line 422 and it seems OK.

Is that correct ?

OS version :
-------------
Windows 10

**Comment by honir** [comment]
Can you try version 1.1.2 of XMLTV. 
If the problem still occurs please can you tell me on which bouquet and channel the problem occurs.

**Comment by knowledgejunkie** [comment]
I tested tv_grab_fr yesterday against the "Free" bouquet with all channels enabled and observed no failures.

However, even if things are working normally again, having sufficient "defensive coding" in a grabber to handle unexpected conditions is desirable.

**Comment by Media38** [comment]
It's OK with 1.1.2 release for all my tests (Free, TNT, Belgium, ...). I let this issue open for seven days in case of the problem occurs with special datas on the site web the 19 of april.

**Comment by Media38** [comment]
No more troubles with 1.1.2 release

**Comment by honir** [comment]
Duplicate of #174

**Comment by melall** [comment]
On Mac (10.14.6, Mojave) I got the same error but only in --slow mode:

```
$ tv_grab_fr --version
XMLTV module version 1.1.2
This is tv_grab_fr version 1.1.2
$ tv_grab_fr --days 1 --slow --output ~/.xmltv/fr-tv-listings-slow.xml
Getting listings...: Can't call method "look_down" on an undefined value at /opt/local/bin/tv_grab_fr line 637.
```
If I look to the end of the generated file I have:
```
  <channel id="tv5mondefbs.telestar.fr">
    <display-name lang="fr">TV5 MONDE FBS</display-name>
```
Which is the last channel in my configuration. This suggest we cannot grab the first program.
With another configuration with all channels I get the same error.
I used the "Free" configuration option.

Any idea on how to correct this?

**Comment by honir** [comment]
@melall Please can you open a new issue for this (it's not the same error).
