### ISSUE TITLE
Installing xmltv on Windows

### ISSUE THREAD

**Issue by misar1** [XMLTV/xmltv#178]
I originally installed xmltv by downloading the Version 1.0.0 zip file from SourceForge. This extracts to a simple folder set in which xmltv.exe is one component. I subsequently upgraded to versions 1.1.0, 1.1.1 and 1.1.2 by downloading the new binaries from the GitHub website and replacing xmltv.exe in the folder set obtained from the zip file. 

This works correctly but I have two questions for the developers.
Are the contents of the zip file necessary or can the GitHub binaries be used as standalone programs?
Why is the SourceForge download not updated, especially if it is needed to run xmltv on Windows?

The SourceForge website currently has over 100 downloads per week of the February 2021 version and I suspect many of those users have no idea that later versions are available. Even if they find their way to GitHub a typical Windows user would probably look at the website contents and give up.

**Comment by rmeden** [comment]
On 4/23/2022 4:20 AM, misar1 wrote:
>
> I originally installed xmltv by downloading the Version 1.0.0 zip file 
> from SourceForge. This extracts to a simple folder set in which 
> xmltv.exe is one component. I subsequently upgraded to versions 1.1.0, 
> 1.1.1 and 1.1.2 by downloading the new binaries from the GitHub 
> website and replacing xmltv.exe in the folder set obtained from the 
> zip file.
>
> This works correctly but I have two questions for the developers.
> Are the contents of the zip file necessary or can the GitHub binaries 
> be used as standalone programs?
>

The only file actually needed on Windows is xmltv.exe   All the other 
files are documentation.  The latest xmltv.exe was usually 
https://alpha-exe.xmltv.org, but now xmltv.exe's are automatically 
generated (yea Gary!) as "artifacts" on github commits.

> Why is the SourceForge download not updated, especially if it is 
> needed to run xmltv on Windows?
>
Because we missed it.. :)  You're the first person to mention it. We're 
pretty much all on github now.  I'll look into what we can do.

> The SourceForge website currently has over 100 downloads per week of 
> the February 2021 version and I suspect many of those users have no 
> idea that later versions are available. Even if they find their way to 
> GitHub a typical Windows user would probably look at the website 
> contents and give up.
>
If they look at xmltv.org, they'd be sent to github, but yeah, SF needs 
to be fixed.  I'm on it!

Robert

**Comment by misar1** [comment]
Thanks for the explanation.

While updating SourceForge it might be worth adding a direct link to the release page. I know the code page has a Releases section in the RH sidebar but that page is a bit daunting for Windows users.
