### ISSUE TITLE
Ownership of tvguide.co.uk website

### ISSUE THREAD

**Issue by misar1** [XMLTV/xmltv#185]
Regular users of the excellent grabber should be aware that the website has been bought by Digital Mash which "plans to integrate TV Guide into its existing tech platform". If nothing else the grabber may need substantial modification, depending on what the "integration" entails.

**Comment by garybuhrmaster** [comment]
> that the website has been bought by Digital Mash

Technically, as I understand it, Digitalbox, which operates websites such as Daily Mash and Entertainment Daily.

> If nothing else the grabber may need substantial modification, depending on what the "integration" entails.

Perhaps, perhaps not (we will all have to see), although one of the requirements for completion of the purchase is an "upgrade" of the existing website (for which the current owner will be provided some initial funding, with a larger amount when complete, and the work to be complete in three to six months), and the purchaser prides itself in being 100% mobile focused.  While I admit that the term "upgrade" can send a chill down my spine, sometimes things work out fine, or even better than fine.

But it is certainly something to keep one's eyes on.

**Comment by honir** [comment]
Subsumed within #214
