### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by ovladuk** [XMLTV/xmltv#186]
does this still work? I'm trying to get UKTV but it doesn't get anything atall

**Comment by mkbloke** [comment]
Does what still work?  You should fill in the issue form correctly so people have the necessary info to help.

If you're talking about the grabber for tvguide, it's working fine.

**Comment by ovladuk** [comment]
yes im talking about the grabber. i thought this whole thing was just an EPG grabber?

but yeah it's not grabbing anything when trying to extract uk listings.

im using the command  "C:\xmltv\xmltv.exe tv_grab_uk_tvguide --days 2 --output uk.xml"

and i just get this.

Fetching listings:   0% [*                                                                                            ]No schedule found
Fetching listings:   0% [= *                                                                                          ]No schedule found
Fetching listings:   0% [=    *                                                                                       ]No schedule found
Fetching listings:   0% [=       *                                                                                    ]No schedule found
Fetching listings:   0% [=          *                                                                                 ]No schedule found
Fetching listings:   0% [=             *                                                                              ]No schedule found
Fetching listings:   0% [=               *                                                                            ]Fetching listings:   0% [=                  *                                                                         ]Fetching listings:   0% [=                     *                                                                      ]

**Comment by rmeden** [comment]
There are many EPG grabbers in the XMLTV project.  Based on your command, you're talking about tv_grab_uk_tvguide

Make sure you're using the latest xmltv.exe release

I just tried it and it seems to be working fine.  Maybe you need to run with --configure

**Comment by Bussterj** [comment]
> yes im talking about the grabber. i thought this whole thing was just an EPG grabber?
> 
> but yeah it's not grabbing anything when trying to extract uk listings.
> 
> im using the command "C:\xmltv\xmltv.exe tv_grab_uk_tvguide --days 2 --output uk.xml"
> 
> and i just get this.
> 
> Fetching listings: 0% [* ]No schedule found Fetching listings: 0% [= * ]No schedule found Fetching listings: 0% [= * ]No schedule found Fetching listings: 0% [= * ]No schedule found Fetching listings: 0% [= * ]No schedule found Fetching listings: 0% [= * ]No schedule found Fetching listings: 0% [= * ]Fetching listings: 0% [= * ]Fetching listings: 0% [= * ]

Just say no to the first listing I had the same problem and I checked my listing and the first one had an & symbol in it preventing it from continuing
