### ISSUE TITLE
tv_grab_fi fails when fetching from Yle

### ISSUE THREAD

**Issue by hertell** [XMLTV/xmltv#2]
When using yle as a source, the fetching-process fails with the following error:
fetchRaw(): could not fetch https://areena.yle.fi/tv/opas?t=2018-01-08, error: 500 Can't connect to areena.yle.fi:443, aborting
 at ./tv_grab_fi line 1466

When running "./tv_grab_fi --list-channels" i get the next error:
fetchRaw(): could not fetch https://areena.yle.fi/tv/opas, error: 500 Can't connect to areena.yle.fi:443, aborting
 at ./tv_grab_fi line 1411l

**Comment by knowledgejunkie** [comment]
Please can you recheck to see if this was an issue with network connectivity. Please also confirm that you are using XMLTV 0.5.70.

I have just checked using the default test.conf for tv_grab_fi (which contains several yle channels) and it worked without any problems.

tv_grab_fi --list-channels also worked as expected with no errors.

**Comment by hertell** [comment]
I have the latest git-version, but the tv_grab_fi shows me the 0.5.61-version. Not sure if i messed up something, or if there is a bug showing the vrong version for tv_grab_fi..

$ git pull
Already up-to-date.

$git log
commit da085fb3117c4b5192f326b6a27d9e230f7e7f4d
Author: Nick Morrott <knowledgejunkie@gmail.com>
Date:   Sun Jan 21 21:23:26 2018 +0000

    git: remove CVS references from gitignore
...
$ grab/fi/tv_grab_fi --version
XMLTV module version 0.5.61
This program version generated from
        common.pm
        day.pm
        foxtv.pm
        iltapulu.pm
        programme.pm
        programmeStartOnly.pm
        telkku.pm
        tv_grab_fi.pl
        yle.pm

**Comment by knowledgejunkie** [comment]
When I build and run tv_grab_fi from within the build tree (perl Makefile.PL; make), I see the following output:

$ perl -I blib/lib blib/script/tv_grab_fi --version
XMLTV module version 0.5.70
This program version generated from
        common.pm                 1f06fa3d  2017/07/12  19:33:02
        day.pm                    2ebf3e92  2014/06/14  18:18:36
        foxtv.pm                  1f06fa3d  2017/07/12  19:33:02
        iltapulu.pm               b9371d01  2015/11/20  20:19:21
        programme.pm              8b2f6552  2016/08/20  16:55:13
        programmeStartOnly.pm     db36b28a  2016/05/16  16:20:29
        telkku.pm                 8b2f6552  2016/08/20  16:55:13
        tv_grab_fi.pl             b46a0872  2014/06/21  16:36:15
        yle.pm                    be0cf446  2017/10/07  20:39:00

Maybe you have some old installed XMLTV libraries somewhere in your library search path?

$ find /usr -name XMLTV.pm

**Comment by hertell** [comment]
YEp, you're right. in /usr/share/perl5/XMLTV.pm is the  0.5.61-version. Running tv_grab_fi from grab/fi/tv_grab_fi used the system-module. 

Running now the grab-process as
perl -I blib/lib blib/script/tv_grab_fi 
Still gives me errors:
fetchRaw(): could not fetch https://areena.yle.fi/tv/opas?t=2018-02-13, error: 500 Can't connect to areena.yle.fi:443, aborting

I wonder if Yle is blocking access based on user agent, because i can open the link with my browser. If i got it right from the source, tv_grab_fi does not have an '--agent' parameter for setting a custom $ua->agent? 

ps. I did obviously btw not know how to run tv_grab_fi in a way that i use the right source. This could maybe be mentioned in the readme for dummies like me? .-)

**Comment by knowledgejunkie** [comment]
Please could you:
- attach your tv_grab_fi config file that's causing the problems
- confirm you have HTTPS support for LWP installed

> ps. I did obviously btw not know how to run tv_grab_fi in a way that i use the right source. This could maybe be mentioned in the readme for dummies like me? :-)

Instructions for running the grabber from within the build root, instead of running `make install`, could be added but it is anticipated that regular users follow the normal `perl Makefile.PL && make && make test && make install` routine.

**Comment by hertell** [comment]
This got now embarrassing.. I was missing LWP::Protocol::https and had also a quite old verson of LWP::UserAgent (i think it was 6.03).

After upgrading LWP::UserAgent and installing LWP::Protocol::https, all seems now to work as it should :-) !
