### ISSUE TITLE
The locale codeset (cp1250) isn't one that perl can decode

### ISSUE THREAD

**Issue by skom27** [XMLTV/xmltv#201]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
xmltv-1.2.1-win64
…

XMLTV Component?
----------------
tv_grab_eu_epgdata, tv_grab......
…

Perl Version
------------
perl 5, version 36, subversion 0 (v5.36.0) built for MSWin32-x64-multi-thread

Operating System
----------------
Windows 10 Pro 22H2

What happened?
--------------
Can't run any grabber

What did you expect to happen?
------------------------------
Run grabber

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
…(Please paste any warnings/errors, if available)
The locale codeset (cp1250) isn't one that perl can decode, stopped at C:\Users\Kk\AppData\Local\Temp\par-4b727a797369656b\cache-da6026af419c0de4f450523a7fe25300b02100ad\inc\lib/Encode/Locale.pm line 120.
Compilation failed in require at C:\Users\Kk\AppData\Local\Temp\par-4b727a797369656b\cache-da6026af419c0de4f450523a7fe25300b02100ad\inc\lib/LWP/UserAgent.pm line 1100.
Compilation failed in require at C:\Users\Kk\AppData\Local\Temp\par-4b727a797369656b\cache-da6026af419c0de4f450523a7fe25300b02100ad\inc/script/tv_grab_eu_epgdata line 145.
BEGIN failed--compilation aborted at C:\Users\Kk\AppData\Local\Temp\par-4b727a797369656b\cache-da6026af419c0de4f450523a7fe25300b02100ad\inc/script/tv_grab_eu_epgdata line 145.

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. xmltv tv_grab_eu_epgdata --configure --output a.xml
2. xmltv tv_grab_uk_tvguide --configure --output b.xml…
3. …

Please attach your config file below:
-------------------------------------
(Remember to remove any usernames/passwords)
Can't create configuration file

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
…

**Comment by misar1** [comment]
Run the commands in a command window (console) after changing the codepage by using, eg
chcp 65001
It will only change within that command window.

**Comment by honir** [comment]
There's a new version our [Releases page](https://github.com/XMLTV/xmltv/releases/tag/v1.2.1)

Please give it a try and see if it fixes your issue.
