### ISSUE TITLE
Help With XMLTV / Emby Upgrade

### ISSUE THREAD

**Issue by AnythingOldSkewl** [XMLTV/xmltv#202]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
1.1.0.0
…

I hope someone can help. I am kind of new to XMLTV. I use the plugin version on Emby. I also use Emby on my seedbox. My problem is Emby is using a very old plugin version of XMLTV. I can't just use the files from Git to update it on Emby. Is there anyone programming from XMLTV to help push a newer update to Emby? I'd appreciate it.

**Comment by rmeden** [comment]
Have you spoken with the Emby folks?  Emby may just be using the XMLTV data format and not a grabber, so that's all Emby code. If they are packaging an XMLTV grabber, they can probably tell you how to update it.

**Comment by AnythingOldSkewl** [comment]
> Have you spoken with the Emby folks? 

I'm just understanding IPTV. I really don't know any thing about "grabbers," also I think I understand what you mean. I believe it's a programmer who must contributed to the Emby community. if I can discover who this person is, maybe I can get help. But there is very little information.

**Comment by honir** [comment]
Turning this into an XY problem...

Why do you want to update the plugin version in Emby? What 'problem' do you hope to solve by doing that?

**Comment by rmeden** [comment]
What did you pay Emby for? Emby Premier?  If so, what is a XMLTV file used for?  Emby Premier provides guide data.   

As honir said, what's the problem you're trying to solve.  Maybe they provide guide data in a modified XMLTV format (set up for streaming and VOD) and normal XMLTV tools wouldn't even work with Emby XMLTV.

**Comment by AnythingOldSkewl** [comment]
> Turning this into an XY problem...
> 
> Why do you want to update the plugin version in Emby? What 'problem' do you hope to solve by doing that?

Because I discovered that XMLTV is only grabbing EPG data from a single IPTV category/playlist. It obviously needs an update. Now, either the programmer who setup the plugin doesn't support it anymore, or Emby is just too lazy to update it because there isn't enough demand for it.

**Comment by rmeden** [comment]
> Because I discovered that XMLTV is only grabbing EPG data from a single IPTV category/playlist.

Who's your IPTV provider?  What is the single IPTV category/playlist you're talking about.   As I mentioned, XMLTV is both a file format and a series of tools (some of which download schedule data).  It's possible your IPTV service is providing an XMLTV formatted feed and that's the problem.  

You can't say "XMLTV is only grabbing", because there is no tool called XMLTV.  For example,  tv_grab_uk_tvguide is an XMLTV project distributed tool that gets data from the UK TVGuide website.   What is the tool in use?  If you don't know, maybe the Emby folks can tell you how Emby works.

**Comment by honir** [comment]
Emby have developed their own software (their "plugin") to interface to EPG suppliers who use the XMLTV file format. Their only connection with xmltv.org (i.e. this website) is that they use our file format. We did not write their software (which is not open source). Using our Git files will not help you (as Emby use their own software, not ours).

Your problem will most likely be an issue with wherever you are getting your EPG data. You might check with them whether they are, in fact, providing data in the correct XMLTV format, or whether it is some other format. This is outside our sphere of influence.

The [Emby community forum](https://emby.media/community/index.php) seems quite active and helpful.

Sorry we can't be of any help to you here.
