### ISSUE TITLE
tv_grab_na_dtv Decoding JSON response failed. Error getting channel list: check your zip code

### ISSUE THREAD

**Issue by Dukat-Gul** [XMLTV/xmltv#212]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
./tv_grab_na_dtv --version
XMLTV module version 1.2.1
This is tv_grab_na_dtv version 1.2.1

even tried a fresh git clone on
Wed 09 Aug 2023 11:53:59 AWST

XMLTV Component?
----------------
/xmltv/grab/na_dtv//tv_grab_na_dtv

Perl Version
------------
perl --version

This is perl 5, version 36, subversion 0 (v5.36.0) built for x86_64-linux-gnu-thread-multi
(with 52 registered patches, see perl -V for more detail)

Operating System
----------------
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
uname -a
Linux 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-1 (2023-07-14) x86_64 GNU/Linux

What happened?
--------------
when I run tv_grab_na_dtv and reference an existing configuration file - or even if I try and created a new with --configure 

./tv_grab_na_dtv --configure
Enter your zip code to include local channels.
Zip Code: 90210
The timezone that you live in.
Time Zone:
0: America/New_York
1: America/Detroit
**EDITED**
28: Pacific/Honolulu
Select one: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28 (default=0)] 1
Decoding JSON response failed.
Error getting channel list: check your zip code

What did you expect to happen?
------------------------------
About a month ago it was fully operational, and I would be asked (for the --configuration) to select which channels to include in the configuration file. If it was run against a working configuration file it would grab the XML episode data.

Did you see any warnings/errors?
--------------------------------
Decoding JSON response failed.
Error getting channel list: check your zip code

if I run with --debug
https://pastebin.com/BeX0hsXg

What steps are needed to reproduce this issue?
----------------------------------------------

1. …git clone https://github.com/XMLTV/xmltv
2. …cd grab/na_dtv
3. …./tv_grab_na_dtv --configure

Please attach your config file below:
-------------------------------------
Config is at the bottom of https://pastebin.com/BeX0hsXg

Any other information?
----------------------
Has been working well until about a month ago and then it stopped. Tried to update to 1.2.1 and latest without improvement.

**Comment by Herrminator** [comment]
`curl --fail --max-time 30 -A "xmltv/1.2.1" "https://www.directv.com/json/channels"`
returns
`curl: (22) The requested URL returned error: 404`
Did they deactivate their API?

**Comment by Dukat-Gul** [comment]
I wonder if this could be helpful... 

[https://github.com/iptv-org/epg/issues/2038](url) Discusses how others had to interface due to them checking some extra headers... Accept-language and Connection... perhaps need to be introduced 

[https://github.com/iptv-org/epg/commit/684251ed8315cb6a1131dbe590110f597d6cef43](url) 

Im not sure how the equivalent can be modified in the grab code. I hope someone else can suggest a method.

**Comment by knowledgejunkie** [comment]
Having read the updated thread I was going to do this later anyway - feel free to remove it!
