### ISSUE TITLE
tv_grab_ch_search: needs URL update

### ISSUE THREAD

**Issue by angelaschmid** [XMLTV/xmltv#215]
The grabber gets only partial data, maybe just from a default page with some default channels, but not for all the channels from the configuration file.

https://tv.search.tv changed to https://search.ch/tv

Please adapt:
```
    'source-data-url'      => 'https://search.ch/tv/channels',
    'source-info-url'      => 'https://search.ch/tv',
```

**Comment by misar1** [comment]
@honir Unfortunately you removed the error message but the result is the same:
Timezone is +0100
Fetching listings:   0% [                                                                                             ]

I noticed that it always writes a single cache entry (attached) for BBC One London - even after I deleted that channel from the .conf list. That does not seem right and anyway it does not generate an XML for that channel.

[07cd930ed011bc60ff68e19f2f2eccb2.zip](https://github.com/XMLTV/xmltv/files/12658327/07cd930ed011bc60ff68e19f2f2eccb2.zip)

**Comment by honir** [comment]
What is your version of XMLTV?

Which channel(s) are missing?

**Comment by zyll71** [comment]
Can confirm the issue. About half of the channels are not receiving data, possibly more.
The proposed fix works for me. My version is 1.1.1-1 (Ubuntu repo).

**Comment by bhaak** [comment]
Can confirm both the issue as well as the fix.

Shows you how many different tv stations  I need these days. :)

Thanks for the report.
