### ISSUE TITLE
Samsung iptv apps not loading xmltv file

### ISSUE THREAD

**Issue by liben96** [XMLTV/xmltv#218]
Hi guys,

I have tried my xmltv file in different iptv apps in my samsung tv, and i am not able to make it work.

The xml looks fine, however none of these apps display the epg, although im loading correctly my file.

Any ideas what could be happening

Operating System
----------------
Samsung TV

What happened?
--------------
EPG not loading

What did you expect to happen?
------------------------------
It should load the epg data from my xmltv file

Did you see any warnings/errors?
--------------------------------
No errors or warning.

What steps are needed to reproduce this issue?
----------------------------------------------
1. Install any samsung iptv app
2. Add a playlist
3. Add url of xmltv file

**Comment by rmeden** [comment]
how is this not a bug in the Samsung app?

**Comment by honir** [comment]
It is likely the Samsung app/tv is not using valid XMLTV format. These IP-TV apps are notorious for using proprietary data formats (to stop people re-using their data elsewhere).
