### ISSUE TITLE
Could tv_grab_uk_tvguide screen scraping be reinstated?

### ISSUE THREAD

**Issue by spider3838** [XMLTV/xmltv#219]
XMLTV Version?
--------------
1.2.1

XMLTV Component?
----------------
tv_grab_uk_tvguide

Perl Version
------------
5.36.0

Operating System
----------------
Raspbian GNU/Linux 12 (bookworm), kernel Linux 6.1.0-rpi4-rpi-v7, architecture arm

What happened?
--------------
Since early September 2023 the TVGuide web site changed its format significantly and the screen scraping version of the Perl script stopped working. Subsequent forays into using the API met limited success but the API now seems to not be working for their own app. Could the web page screen scraping be reinstated?

What did you expect to happen?
------------------------------
I have cobbled together some quick and dirty Java (using JSoup) which retrieves listings on a daily basis for a configurable list of channels and number of days then gets season and episode details for each programme. I am happy to share my Java code if it could help getting the Perl screen scraping code rewritten. I'm a pensioner with limited funds, so don't want to go down the paid for schedulesdirect.org route.

Any other information?
----------------------
Has been persistent since screen scraping broke in September 2023

**Comment by honir** [comment]
You are unlikely to get someone willing to spend time writing a new grabber for this, especially when TVGuide have made it clear they don't want us taking their data so will likely block any new grabber as soon as it is released.

The days of screen-scraping for guide data are rapidly coming to an end. The fashion towards "rich user experience" (what nonsense!) has effectively killed-off simple screen-scraping.

I would urge you to consider Schedules Direct. The grabbers for this are actively maintained, and the guide data are excellent. It costs a mere £28 a year, which is £2.30 a month. About half a pint of beer.
