### ISSUE TITLE
tv_grab_pt_vodafone: Invalid local time for date in time zone: Europe/Lisbon

### ISSUE THREAD

**Issue by higuita** [XMLTV/xmltv#22]
The tv_grab_pt_vodafone grabber is returning this:

Invalid local time for date in time zone: Europe/Lisbon

On 2016/03/25 at 01h, Portugal will switch to the summer daylight time and looking to the json returned we have this:

```
          {
            "startTime": "0:04",
            "episodeInfo": "",
            "sid": "1_1521936240000",
            "programDetails": "Depois da queda do Muro de Berlim, Katrine, filha de mãe norueguesa e de um soldado alemão da ocupação, vê a sua vida desmoronar-se. Isto porque se 
recusa a testemunhar contra o Estado norueguês a favor das apelidadas crianças da guerra.",
            "duration": 114,
            "endMillis": 1521943080000,
            "serid": null,
            "programTitle": "Duas Vidas",
            "pid": "1171170",
            "endTime": "2:58",
            "date": "25-03-2018"
          },
```

So vodafone is delivering the start/end dates already in the correct daylight time, so i would say that we should remove the `time_zone` lines in the grabber

Local test this solves the problem. I do not know when the daylight change goes backwards, what data the json will have, but we will find out in half a year! :)

**Comment by honir** [comment]
Thanks for the report. This will be fixed in the next release, or you can download a fixed version [here](https://github.com/XMLTV/xmltv/blob/master/grab/pt_vodafone/tv_grab_pt_vodafone)

**Comment by higuita** [comment]
Thanks @honir , works perfectly!

**Comment by honir** [comment]
You're welcome.  p.s. good work on the original shell script - I do love a nice regex!  ;-)
