### ISSUE TITLE
Edit tv_grab_url to follow redirects

### ISSUE THREAD

**Issue by henrydatei** [XMLTV/xmltv#237]
I'm coming from TvHeadend which I installed via Docker from Linuxserver. In the dockerfile there I found that they are installing xmltv, so I guess this is the right place for my question. If not, please give me a hint where I can find help.

TVHeadend gives the opportunity to grab XMLTV data with what they call "XMLTV: XMLTV URL grabber". Internally this just calls `tv_grab_url`, a script which uses `curl` to download XMLTV data from the URL which you provide to the "XMLTV: XMLTV URL grabber". I want to use https://xmltv.info/de/epg.xml as a provider. The problem is now, that this XMLTV provider generates a unique link for every request, so if you request https://xmltv.info/de/epg.xml you get a redirect to https://xmltv.info/de/epg.xml/e4aed9d33f528a05dd3fa1ed2f8b3ef3 and here you get the XMLTV data. After accessing this link is  invalid. So for tv_grab_url to function with this provider it needs to follow redirects. If you look in the script `tv_grab_url` code you find the line
```shell
curl -s "$URL"
```
but to follow redirects it should be
```shell
curl -sL "$URL"
```
Where can I make a pull request to suggest the change?

**Comment by honir** [comment]
> I'm coming from TvHeadend which I installed via Docker from Linuxserver.

I'm guessing you need to be reporting this at [`linuxserver/docker-tvheadend`](https://github.com/linuxserver/docker-tvheadend/issues)

**Comment by garybuhrmaster** [comment]
I am going to close this issue, as it is a tvheadend issue (their script, their issue).
