### ISSUE TITLE
tv_grab_uk_freeview cache location

### ISSUE THREAD

**Issue by misar1** [XMLTV/xmltv#240]
@honir, This is not really an issue but I cannot find another way to ask you a question.

I run xmltv.exe at a command prompt in Windows from a location such as d:\xmltv. Previously (using tvguide.co.uk) I set the cache location using an entry such as "cachedir=d:\xmltv\cache" as the first line of each .config file. That no longer works and I cannot find the location being used (including the previous default in the hidden user appdata folders). However, while testing with the --debug switch the folder "d:\tmp\.xmltv\cache" was created and used. This is never used without --debug.

Did you remove the cachedir= option and where is the current cache?

Thanks.

**Comment by misar1** [comment]
OK, I think I worked out the answers by comparing the old and new scripts
 - I cannot find a cache location in normal usage because the EPG is no longer cached and hence cachedir is redundant!
Making the original cache mode a debug only option is OK for me because I would rarely repeat the same grab within one day.

Assuming I got it right, my apologies  for troubling you.😊

**Comment by honir** [comment]
Sometimes, it can be useful to cache static data -- such as programme descriptions -- but that's not needed here.

Unless you are running multiple times an hour then caching is just a waste of time.

**Comment by misar1** [comment]
Would be interesting to know why you re-instated using the cache by default.
Anyway, I noticed that previous files are not deleted even when a programme is a couple of days out of date so the number is growing rapidly. Is that by design?

**Comment by honir** [comment]
Items are removed from the cache 24 hours after they were last requested, when the program exits.

**Comment by misar1** [comment]
Its running at the moment so will check when the run completes but I still have all the entries from the 14th. 
Did you notice my question about re-instating the cache by default? Just curious. 😊
