### ISSUE TITLE
tv_grab_uk_freeview icons not fetchable as-is

### ISSUE THREAD

**Issue by nhathaway** [XMLTV/xmltv#242]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
1.1.1 (but with tv_grab_uk_freeview from github main)

XMLTV Component?
----------------
tv_grab_uk_freeview

Perl Version
------------
5.34.0

Operating System
----------------
Ubuntu 22.04

What happened?
--------------
The icon URLs produce errors

What did you expect to happen?
------------------------------
The icon URL should result in the icon being fetched

Did you see any warnings/errors?
--------------------------------
No

What steps are needed to reproduce this issue?
----------------------------------------------
tv_grab_uk_freeview
[tv_grab_uk_freeview.zip](https://github.com/user-attachments/files/16757751/tv_grab_uk_freeview.zip)

Please attach your config file below:
-------------------------------------
Attached...

Any other information?
----------------------
The icon URL needs to have a parameter added on the end, namely ?w=160 or ?w=800 (width in pixels, I believe). Typically, you might want the channel icons to be 160 and the programme icons to be 800, but that is down to choice.

**Comment by honir** [comment]
Thanks for the report, and for the solution! :-)

I've added params to the config file which will add the img width value as a query string to the icon urls.
So
`iconc=?w=160`
`iconp=?w=800`
in the conf file sets, respectively, the widths of the channel and programme icons. Manually edit your conf file to add/change these if you want (optional - defaults to the above if not found in conf found).
