### ISSUE TITLE
MythTV Grabbing XMLTV data using tv_grab_na_tvmedia is not supported. 

### ISSUE THREAD

**Issue by ncp1113** [XMLTV/xmltv#245]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
(Please specify release version or git commit ID)
…
1.3.0-1

XMLTV Component?
----------------
(Grabber name or utility)
…
tv_grab_na_tvmedia

Perl Version
------------
v5.38.2

Operating System
----------------
Ubuntu 24.04.1 LTS

What happened?
--------------
Running mythfilldatabase I get errors:
E  tv_grab_na_tvmedia  --capabilities failed or we timed out waiting. You may need to upgrade your xmltv grabber
E  Grabbing XMLTV data using tv_grab_na_tvmedia is not supported. You may need to upgrade to the latest version of XMLTV.
Also on every channel:
E  XMLTV grabber returned error code 1
E  Malformed XML file, missing </tv> element, at line 1, Premature end of document.
E  Failed to fetch some program info

What did you expect to happen?
------------------------------
successful fill of database

FYI: mythfilldatabase version: fixes/34 [v34.0+fixes.20240210.e3e165a1-0ubuntu6]
       mythtv version: 2:34.0+fixes.20240210.e3e165a1-0ubuntu6

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)

What steps are needed to reproduce this issue?
----------------------------------------------
mythfilldatabase --verbose

Please attach your config file below:
-------------------------------------
(Remember to remove any usernames/passwords)
apikey=***
lineup=7716

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
I recently reinstalled mythtv. I got some guide data at first, just for the first few hours of data, then blank. I ran mythtfilldatabase from the command line with the backend off. I tried it both as my user and mythtv user and also with sudo. My connection to the mythtv database is good.

**Comment by rmeden** [comment]
www.tvmedia.ca  wrote the grabber to pull from their service.  If they don't respond to this ticket, you may want to try contacting them.

**Comment by garybuhrmaster** [comment]
> E tv_grab_na_tvmedia --capabilities failed or we timed out waiting. You may need to upgrade your xmltv grabber

This is likely the first thing to address (and it is basic, it just runs the grabber with the --capabilities flag).  Most likely either the user that is trying to run the grabber does have the grabber in the path, or it does not have permissions to run it.  You may also be able to get assistance from the mythtv community (they probably have many other suggestions).

**Comment by ncp1113** [comment]
I ran it from the command line both is my user and as the mythtv user. If it wasn't in the path, I would have gotten an error. I also tried running it with sudo.

**Comment by ncp1113** [comment]
I ran it today and it worked. I'm wondering if maybe their server was down.
