### ISSUE TITLE
xmltv (se-tvzon) not working after windows update.

### ISSUE THREAD

**Issue by rco133** [XMLTV/xmltv#25]
Hi.

Today I updated my Windows 7 from Windows update, and suddenly xmltv is no longer working.

I am using the tv_grab_se_tvzon grabber.

If I am using this at the top of the cfg file: root-url=http://xmltv.xmltv.se/channels-Denmark.xml.gz
I am getting the following:

Failed to fetch http://xmltv.xmltv.se/channels-Denmark.xml.gz at /<E:\rene\temp\
tv-stuff\xmltv_5_70\xmltv.exe>grab/se_tvzon/tv_grab_se_tvzon line 346.

If I change the top of the cfg file to:  https://xmltv.xmltv.se/channels-Denmark.xml.gz
I am getting the following:

E:\rene\temp\tv-stuff\xmltv_5_70>xmltv.exe tv_grab_se_tvzon --days 10 --quiet --
config-file E:\rene\temp\tv-stuff\xmltv_5_70\.xmltv\tv_grab_se_tvzon.conf --outp
ut list.xml
Failed to download data for zulu.tv2.dk on 2018-06-14.
Failed to download data for zulu.tv2.dk on 2018-06-15.
Failed to download data for zulu.tv2.dk on 2018-06-16.
Failed to download data for zulu.tv2.dk on 2018-06-17.
Failed to download data for zulu.tv2.dk on 2018-06-18.
Failed to download data for zulu.tv2.dk on 2018-06-19.
Failed to download data for zulu.tv2.dk on 2018-06-20.
Failed to download data for zulu.tv2.dk on 2018-06-22.

The only difference is http vs https

I have only enabled one channel in the config file.

Why the grabber is able to download data for 2018-06-21 I don't know.

I have another PC where Windows 7 hasn't been updated. On that one xmltv is still working like normal, and it doesn't matter wether the link has http or https.

Any idea whats going on?

rco133

**Comment by rco133** [comment]
Hi.

I tried to delete everything in the xmltv cache folder, and then everything seems to be working.

However, it still doesn't Work if I use http and not https.

Before the Windows 7 update http worked fine as well.

rco133

**Comment by jnylen** [comment]
This should've been posted to xmltv-se org on gitlab.

This should be fixed now. SSL issues.
