### ISSUE TITLE
 tv_grab_zz_sdjson output is in XML, not JSON

### ISSUE THREAD

**Issue by redaters** [XMLTV/xmltv#255]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
XMLTV module version 1.3.0
This is tv_grab_zz_sdjson version 1.3.0

XMLTV Component?
----------------
tv_grab_zz_sdjson 

Perl Version
------------
perl5 (revision 5 version 38 subversion 2)

Operating System
----------------
Ubuntu 24.04.1 LTS

What happened?
--------------
When running the tv_grab_zz_sdjson command, the output is in XML format, similar to the tv_grab_na_dd output

What did you expect to happen?
------------------------------
json format

Did you see any warnings/errors?
--------------------------------
No errors

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1 - tv_grab_zz_sdjson --config-file tv_grab_zz_sdjson.conf --days 14 --output current_listing.json
2 - cat current_listing.json 

output:

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv source-info-url="http://www.schedulesdirect.org" source-info-name="Schedules Direct" generator-info-name="tv_grab_zz_sdjson 1.3.0">
  <channel id="I101322.labs.zap2it.com">
    <display-name>WDVM-DT2</display-name>
    <display-name>WDVMDT2</display-name>
    <display-name>25_2</display-name>
    <icon src="https://schedulesdirect-api20141201-logos.s3.dualstack.us-east-1.amazonaws.com/stationLogos/s89923_dark_360w_270h.png" width="360" height="270" />
  </channel>
  <channel id="I101326.labs.zap2it.com">
    <display-name>WDVM-DT3</display-name>
    <display-name>WDVMDT3</display-name>
    <display-name>25_3</display-name>
    <icon src="https://schedulesdirect-api20141201-logos.s3.dualstack.us-east-1.amazonaws.com/stationLogos/s119814_dark_360w_270h.png" width="360" height="270" />
  </channel>
  <channel id="I102359.labs.zap2it.com">
    <display-name>WJLA-DT4</display-name>
    <display-name>WJLADT4</display-name>
    <display-name>7_4</display-name>
    <icon src="https://schedulesdirect-api20141201-logos.s3.dualstack.us-east-1.amazonaws.com/stationLogos/s102116_dark_360w_270h.png" width="360" height="270" />
  </channel>
  <channel id="I102968.labs.zap2it.com">
    <display-name>WTTG-DT3</display-name>
    <display-name>WTTGDT3</display-name>
    <display-name>5_3</display-name>
    <icon src="https://schedulesdirect-api20141201-logos.s3.dualstack.us-east-1.amazonaws.com/stationLogos/s109454_dark_360w_270h.png" width="360" height="270" />
  </channel>
....

Please attach your config file below:
-------------------------------------
cache=/opt/jellyfin_10.0/jellyfin-config/tv_grab_zz_sdjson.cache
channel-id-format=zap2it
previously-shown-format=date
username=xxx
password=xxx
mode=lineup
lineup=USA-OTA-21157
lineup!USA-OTA-21158

Any other information?
----------------------
New issue. Guide to be used with Jellyfin.

**Comment by rmeden** [comment]
The purpose of tv_grab_zz_sdjson (and all XMLTV grabbers) is to output the XMLTV XML format.  Jellyfin can read an XMLTV formatted file.  It's not supposed to create JSON output.

**Comment by honir** [comment]
The output for all of the grabbers on here is XML.

The 'json' in `tv_grab_zz_sdjson` refers to the fact the source data is the JSON feed from the Schedules Direct (SD) website, not that the output is JSON.
