### ISSUE TITLE
tv_grab_dtv_la stopped working. source url is gone. Possible new sources in comments.

### ISSUE THREAD

**Issue by ctroncoso** [XMLTV/xmltv#27]
Seems that http://directstage.directvla.com/ isn't working any more. 
Possible new source : https://www.directv.com.ar/guia/  <-- seems to be the most complete listing.
Another source might be the ajax call that retrieves the listing:
https://www.directv.com.ar/guia/js/Program-Guide/ProgrammingGuideAjax.js

**Comment by rmeden** [comment]
If you don't want to fight with a scrapper, Schedule Direct's SD-JSON service has Latin America ( tv_grab_zz_sdjson, tv_grab_zz_sdjson_sqlite).   It's not free, but is reliable.

(disclaimer: I'm a founding director of SD, current president)

**Comment by honir** [comment]
Where are you accessing it from? 
I think they implement a geo-block and only allow access from "local" countries.
