### ISSUE TITLE
USA Grab

### ISSUE THREAD

**Issue by luluhoc** [XMLTV/xmltv#36]
Hey,

Can I add somehow US TV guide to grab?

**Comment by rmeden** [comment]
At least 3 grabbers for US data come to mind..  All use Schedules Direct

Using Schedule Direct's SD-DD service:   tv_grab_na_dd
Using Schedule Direct's SD-JSON service:  tv_grab_zz_sdjson and tv_grab_zz_sdjson_sqlite.

In addition, percdata.com has a direct XMLTV feed
 https://username:password@dd.percdata.com/percdata/tvlistings/xmltv?days=1

(disclaimer:  I'm a founding board member of SD and current President... I also run the SD fork, PERC data)
