### ISSUE TITLE
tv_grab_uk_tvguide --days 2 exception in date

### ISSUE THREAD

**Issue by qdacsvx** [XMLTV/xmltv#41]
[prince.html.gz](https://github.com/XMLTV/xmltv/files/2705206/prince.html.gz)
Got channels for --days 1. But for --days 2 (even trying each channel singlely) every channel has an error.

Argument "" isn't numeric in numeric gt (>) at /usr/bin/tv_grab_uk_tvguide line 673.
Use of uninitialized value $a in string eq at /usr/bin/tv_grab_uk_tvguide line 400.
Use of uninitialized value $a in string eq at /usr/bin/tv_grab_uk_tvguide line 401.
Use of uninitialized value $a2 in string eq at /usr/bin/tv_grab_uk_tvguide line 402.
Use of uninitialized value $a2 in string eq at /usr/bin/tv_grab_uk_tvguide line 403.
Validation failed for type named Hour declared in package DateTime::Types (/usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime/Types.pm) at line 101 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Hour declared in package DateTime::Types (/usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime/Types.pm) at line 101 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x55d9b2d880b0)', 'value', undef) called at (eval 224) line 108
DateTime::_check_set_params('hour', undef, 'minute', undef, 'second', 0) called at /usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime.pm line 2050
DateTime::set('DateTime=HASH(0x55d9b44dc298)', 'hour', undef, 'minute', undef, 'second', 0) called at /usr/bin/tv_grab_uk_tvguide line 404
main::fetch_listings at /usr/bin/tv_grab_uk_tvguide line 130

with debugging for channel 1011: (prince is attached)

./tv_grab_uk_tvguide --quiet --debug  --config-file conf/96.conf --days 2  --output xml/1011 && mv xml/1011 X1011 && rm -r /tmp/mm/cache/1011
Fetching http://my.tvguide.co.uk/channellisting.asp?ch=1011&cTime=12%2F21%2F2018%2000%3A00%3A00 from server.
Fetching https://my.tvguide.co.uk/channellisting.asp?ch=1011&cTime=12%2F21%2F2018%2000%3A00%3A00 from server.
Fetching https://www.tvguide.co.uk/detail/2362463/144174578/anand from server.
Fetching https://www.tvguide.co.uk/detail/2985904/145663175/khatta-meetha from server.
Fetching https://www.tvguide.co.uk/detail/137016/145663177/nikaah from server.
Fetching http://my.tvguide.co.uk/channellisting.asp?ch=1011&cTime=12%2F22%2F2018%2000%3A00%3A00 from server.
Fetching https://my.tvguide.co.uk/channellisting.asp?ch=1011&cTime=12%2F22%2F2018%2000%3A00%3A00 from server.
Fetching https://www.tvguide.co.uk/detail/137016/145663177/nikaah from cache without checking with server.
Fetching https://www.tvguide.co.uk/detail/1584620/144175908/dostana from server.
Fetching https://www.tvguide.co.uk/detail/2670689/144175910/fan from server.
Fetching https://www.tvguide.co.uk/detail/160531242/145666246/%C2%A3the-making from server.
Argument "" isn't numeric in numeric gt (>) at ./tv_grab_uk_tvguide line 662.
Fetching https://www.tvguide.co.uk/detail/2928079/144175912/qaidi-band from server.
Fetching https://www.tvguide.co.uk/detail/1874187/144175914/yeh-jawaani-hai-deewani from server.
Fetching https://www.tvguide.co.uk/detail/160592915/145666248/%C2%A3the-making from server.
Fetching https://www.tvguide.co.uk/detail/3117837/144175916/karwaan from server.
Fetching https://www.tvguide.co.uk/detail/3117833/144175918/hate-story-4 from server.
Fetching https://www.tvguide.co.uk/detail/816167/145666251/amanush from server.
Fetching https://www.tvguide.co.uk/detail/160592918/145666253/%C2%A3the-making from server.
Fetching https://www.tvguide.co.uk/detail/160592919/145666255/%C2%A3the-making from server.
Fetching https://www.tvguide.co.uk/detail/1060818/145666257/kaala-patthar from server.
Fetching http://my.tvguide.co.uk/channellisting.asp?ch=1011&cTime=12%2F23%2F2018%2000%3A00%3A00 from server.
Fetching https://my.tvguide.co.uk/channellisting.asp?ch=1011&cTime=12%2F23%2F2018%2000%3A00%3A00 from server.
Fetching https://www.tvguide.co.uk/detail/1060818/145666257/kaala-patthar from cache without checking with server.
Fetching https://www.tvguide.co.uk/detail/3117837/144175924/karwaan from server.
Fetching https://www.tvguide.co.uk/detail/160592920/145666259/%C2%A3the-making from server.
Fetching https://www.tvguide.co.uk/detail/2168128/144175926/dum-laga-ke-haisha from server.
Fetching https://www.tvguide.co.uk/detail/2490599/144175928/krrish-3 from server.
Fetching https://www.tvguide.co.uk/detail/2761852/144175930/62-filmfare-awards-2017 from server.
Fetching https://www.tvguide.co.uk/detail/160592921/145666261/%C2%A3the-making from server.
Fetching https://www.tvguide.co.uk/detail/3106457/144175932/soorma from server.
Fetching https://www.tvguide.co.uk/detail/1838652/144175934/dilwale from server.
Fetching https://www.tvguide.co.uk/detail/2991318/145666263/prince from server.
Use of uninitialized value $a in string eq at ./tv_grab_uk_tvguide line 391.
Use of uninitialized value $a in string eq at ./tv_grab_uk_tvguide line 392.
Use of uninitialized value $a2 in string eq at ./tv_grab_uk_tvguide line 393.
Use of uninitialized value $a2 in string eq at ./tv_grab_uk_tvguide line 394.
Validation failed for type named Hour declared in package DateTime::Types (/usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime/Types.pm) at line 101 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Hour declared in package DateTime::Types (/usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime/Types.pm) at line 101 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x55f290878790)', 'value', undef) called at (eval 224) line 108
DateTime::_check_set_params('hour', undef, 'minute', undef, 'second', 0) called at /usr/lib/x86_64-linux-gnu/perl5/5.26/DateTime.pm line 2050
DateTime::set('DateTime=HASH(0x55f29204da98)', 'hour', undef, 'minute', undef, 'second', 0) called at tv_grab_uk_tvguide line 395
main::fetch_listings at tv_grab_uk_tvguide line 130

**Comment by honir** [comment]
Thanks for the report. This has now been fixed:
https://github.com/XMLTV/xmltv/tree/master/grab/uk_tvguide
