### ISSUE TITLE
Show start/stop time code in tv_grab_uk_tvguide - a simpler alternative?

### ISSUE THREAD

**Issue by mkbloke** [XMLTV/xmltv#43]
Hi,

So, I have noticed that tv_grab_uk_tvguide will not get anything after January 1st because the year of the shows' start/stop times are set to 2018 for anything on January 2nd and beyond.  While it could perhaps be worked around with the existing code, there's already a lot of cruft in there to parse the dates and start/stop times for shows as it is!  I assume that on January 1st, 2019, I'll be able to get data for January 2nd and beyond anyway.

One thing I realised during all this is that the details pages have an "Add to Google Calendar" option.  Part of the link for that, very handily contains the following, as an example:

`dates=20190102T005500Z/20190102T015500Z`

Unless I'm missing something, this would seem like a much cleaner way to extract the date and start/stop times for each show.  Am I missing something?  Any thoughts?

Cheers, Ian

**Comment by honir** [comment]
Thanks for the report. This has now been fixed:
https://github.com/XMLTV/xmltv/tree/master/grab/uk_tvguide

I don't like to rely on using Google stuff as they have a history of pulling the plug if something turns out to not be financially profitable.
