### ISSUE TITLE
Does not access configuration file

### ISSUE THREAD

**Issue by MalcolmClarke** [XMLTV/xmltv#53]
I receive the following error XMLTV::Supplement: Failed to read from C_\Users. The ":" in LOCALAPP is changed to "_"

**Comment by honir** [comment]
What's the command you are running?
What version number of XMLTV?
What version of Windows?

**Comment by knowledgejunkie** [comment]
Closing issue after no response in more than 7 months.

Please re-open the issue, providing the requested details, if this issue persists.
