### ISSUE TITLE
Schedules Direct JSON and XMLTV Python API

### ISSUE THREAD

**Issue by essandess** [XMLTV/xmltv#58]
I wrote a Python API that makes Schedules Direct JSON API calls and wraps the results in an XMLTV EPG file: https://github.com/essandess/sd-py

You all are welcome to use this. I have it working and tested with [EyeTV](../../../../essandess/etv-comskip).

I use the the [lxml](../../../../lxml/lxml) library to make this code relatively fast and efficient.

**Comment by garybuhrmaster** [comment]
Thank you for the reference.  The project is always interested in new contributors and contributions.  However, grabbers to be directly included in this project must currently be written in perl.  References to alternative grabbers (of which there are more than a few) are typically listed on the XmltvRelatedProjects page in the XMLTV wiki.  You should consider adding your python grabber to that page, or if you chose, rewrite your grabber in perl and propose inclusion to this project.

btw, in the case you were not aware, there are three different grabbers (two using the SD-JSON api) in the project that can take Schedules Direct data and create an XMLTV file, but alternatives are always good.

**Comment by rmeden** [comment]
Best place to put it is on the XMLTV.ORG wiki.. request access... be sure and mention you wish to advertise a Python grabber.

**Comment by garybuhrmaster** [comment]
This grabber is now referenced on the wiki, so I am closing this issue.  Thanks.
