### ISSUE TITLE
tv_grab_uk_tvguide: "NO DATA" in MythTV EPG for programmes that span the transition to BST

### ISSUE THREAD

**Issue by mkbloke** [XMLTV/xmltv#59]
XMLTV Version?
--------------
I am using knowledgejunkie's 0.6.1 Debian Sid packages, but with the latest tv_grab_uk_tvguide perl script from GitHub.

XMLTV Component?
----------------
tv_grab_uk_tvguide.

What happened?
--------------
As per the subject, the MythTV EPG shows "NO DATA" for programmes that span the transition to BST.

What did you expect to happen?
------------------------------
The EPG data would show in MythTV for, e.g. "Transporter 3" on Channel 4 and "All New Shocking Moments in Pop" on Channel 5.

Did you see any warnings/errors?
--------------------------------
N/A.

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. `tv_grab_uk_tvguide --debug --quiet --days 1 --offset 1 --output /tmp/tv_guide_tvguide.xml &> /tmp/tv_guide_tvguide.log`

2. `tv_grab_uk_tvguide --debug --quiet --days 1 --offset 2 --output /tmp/tv_guide_tvguide.xml &> /tmp/tv_guide_tvguide.log`

**Comment by mkbloke** [comment]
These programmes appear to have no stop data, e.g.:

`  <programme start="20190330232500 +0000" channel="121">
    <title lang="en">Transporter 3 (2008)</title>
    <desc lang="en">Underworld courier Frank Martin's latest assignment involves transporting the kidnapped daughter of a crooked government minister across Europe on behalf of an eco-terrorist faction. However, a device will kill him if he leaves his car, thugs employed by the politician are out to murder him, and his passenger has a bad case of Stockholm syndrome. Action thriller sequel, with Jason Statham and Natalya Rudakova.</desc>
    <date>2008</date>
    <category lang="en">Adventure</category>
    <category lang="en">Films</category>
    <subtitles type="teletext" />
    <rating system="BBFC">
      <value>15</value>
    </rating>
    <star-rating>
      <value>6.3/10</value>
    </star-rating>
  </programme>
  <programme start="20190330011000 +0000" stop="20190330014000 +0000" channel="148">
    <title lang="en">Teleshopping</title>
    <desc lang="en">A chance to buy goods from the comfort of home.</desc>
    <category lang="en">Advertisement</category>
    <category lang="en">Shopping</category>
    <subtitles type="teletext" />
    <star-rating>
      <value>2.4/10</value>
    </star-rating>
  </programme>`

and:

`  <programme start="20190330221500 +0000" channel="148">
    <title lang="en">All New Shocking Moments in Pop</title>
    <desc lang="en">Clare Grogan narrates a selection of scandalous celebrity moments, including Mariah Carey getting caught out lip synching, the online feud between Madonna and Elton John, Brian Harvey's controversial remarks about Ecstasy and Susan Boyle's misguided hashtag. With contributions from Louis Walsh, Sonia, Cheryl Baker and MC Harvey.</desc>
    <category lang="en">General Show</category>
    <category lang="en">Game Show</category>
    <previously-shown />
    <subtitles type="teletext" />
  </programme>
  <programme start="20190330001500 +0000" stop="20190330010500 +0000" channel="172">
    <title lang="en">Tenable</title>
    <desc lang="en">A family of five from Bath dubbed the Eager Beaverstocks answers questions about top 10 lists from the realms of pop culture and general knowledge, then tries to score a perfect 10 in the final round to take home the prize money. Quiz, hosted by Warwick Davis.</desc>
    <category lang="en">Game Show</category>
    <category lang="en">Quiz</category>
    <episode-num system="xmltv_ns">2.20/60.</episode-num>
    <previously-shown />
    <subtitles type="teletext" />
    <star-rating>
      <value>6.5/10</value>
    </star-rating>
  </programme>`

Compare the first and the next programme in each block.

With apologies for the formatting...

**Comment by honir** [comment]
Thanks for the report.

I've committed a patch which fixes the GMT->BST changeover. But note stop time is an optional attribute, so you should not rely on it being present in the XML output.
