### ISSUE TITLE
tv_grab_pt_vodafone: Invalid local time for DST

### ISSUE THREAD

**Issue by fred-cardoso** [XMLTV/xmltv#61]
Hi,

XMLTV Version?
--------------
Latest prebuilt .exe for Windows

XMLTV Component?
----------------
tv_grab_pt_vodafone

What happened?
--------------
I am using Kodi to read the output from XMLTV, and I am using the tv_grab_pt_vodafone. Although the output EPG file has the time correctly (for e.g. 20190331110000 +0100), on Kodi the program appears to start at 10:00.

Did you see any warnings/errors?
--------------------------------
No

What steps are needed to reproduce this issue?
----------------------------------------------
xmltv tv_grab_pt_vodafone --output="epg.xmltv"

Any other information?
----------------------
I know this issue might not be directly related to XMLTV but I am not sure if it is, or it is not.

What other software are you using?
----------------------------------
Operating System: Windows 10

Thanks!

**Comment by honir** [comment]
Hi,
This isn't an issue with XMLTV, so I suggest you report it on the Kodi forum.

However I know there used to be an issue with Kodi 17 on Windows with this exact problem. I don't know if that was ever fixed or not.
e.g. https://github.com/kodi-pvr/pvr.iptvsimple/issues/158

**Comment by fred-cardoso** [comment]
@honir , after seeing that issue, I can confirm that's it. Thank you for your time!
