### ISSUE TITLE
tv_imdb: Out of Memory

### ISSUE THREAD

**Issue by hirenshah** [XMLTV/xmltv#63]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
0.6.1

XMLTV Component?
----------------
tv_imdb

What happened?
--------------
Out of Memory at Stage 9 when running:
xmltv-v0.6.1-win32.exe tv_imdb --imdbdir D:\IPTV\XMLTV\ --prepStage all --download

What did you expect to happen?
------------------------------
Successful Completion

Did you see any warnings/errors?
--------------------------------

D:\IPTV\XMLTV>xmltv-v0.6.1-win32.exe tv_imdb --imdbdir D:\IPTV\XMLTV\ --prepStage 9
Timezone is +0100
Building indices.  Be warned, this needs a lot of memory for the final stage
(working set about 250 megabytes).

prepStage 7 either has never been run or failed
data for this stage will NOT be added
prepStage 8 either has never been run or failed
data for this stage will NOT be added
indexing all previous stage's data for stage 9..
parsing stage 1 data (movie list)..
reading titles: 100% [======================================================================================]D 0h00m12smerging in stage 2 data (directors)..
merging directors: 100% [===================================================================================]D 0h00m06sOut of memory!

What other software are you using?
----------------------------------
Windows 10 x64 with 32GB RAM

**Comment by hirenshah** [comment]
It always dies on Stage 9, as the memory usage hits 2GB.  I'm not sure what the workaround for this is because even doing it in chucks and running Stage 9 on its own results in the same failure.

**Comment by rmeden** [comment]
I seem to remember this before... When it wants more than 2G of RAM.... The
only workaround may be to not use XMLTV. EXE and build perl locally.

**Comment by hirenshah** [comment]
I actually managed to make this work with a minor workaround.  After a bit of Googling, I found this old program which alters the .exe to enable Large Address Aware:
https://www.techpowerup.com/forums/threads/large-address-aware.112556/

Did that to the xmltv.exe and re-ran the tv_imdb --prepStage all.  Instead of failing with out of memory errors at around 2GB RAM usage, the usage capped out at around 3.3GB.  

Large Address Awareness should be enabled by default in the xmltv.exe and it looks like something straightforward :)

**Comment by garybuhrmaster** [comment]
The 2GB limit for 32-bit windows apps is well known.  However, enabling Large Address Awareness is **NOT** generally recommended by Microsoft and should only be considered once you perform numerous tests to insure that 100% of your program and all libraries and DLL's are >2GB safe (lots of programs historically failed when the address pointer became negative, and it only takes one to ruin the day).  Testing 100% compliance is often difficult (and not testing 100% of the possible code paths can result in different random errors).

I would suggest that the better approach is to stop providing 32-bit EXEs for future versions, and only ship 64 bit apps (W7 ends support in early 2020, and while W8.1 supports 32bit, W8.1 has a very small customer percentage, and while there is a W10 32bit version, upgrading is a click away).

**Comment by hirenshah** [comment]
@garybuhrmaster you are right, and I was surprised that there was no x64 version of the xmltv.exe.  However, regarding Large Address Awareness not being recommended and any potential risks, the program was not functioning for me in the first place so there wasn't much to lose.

**Comment by garybuhrmaster** [comment]
> However, regarding Large Address Awareness not being recommended and any potential risks, the program was not functioning for me in the first place so there wasn't much to lose.

Absolutely.  There was nothing to lose.  I was only responding to the suggestion that LAA should be enabled by default, which it should absolutely **not** be, unless someone does a 100% end-to-end validation (sometimes the core is worse than the disease).  If you have done the 100% end-to-end validation of all grabbers and code paths, please let us know.

**Comment by rmeden** [comment]
Most people who use xmltv.exe use it for grabbers, not tv_imdb.   I don't know how many people depend on the 32 bit version for old computers.  I do use a 32 bit only WinXP VM to build it, but I can probably move to my Win7 desktop.

**Comment by ericwl9** [comment]
I have suffered with the tv_IMDB problem for years!!  My workaround was to build a UBUNTU machine run my database build on it & transfer data back to my WIN10!!!  A true fix would save me a TON of work...

**Comment by hirenshah** [comment]
I came across this issue whilst I was just dabbling and trying to find my way around.... I only raised it because all the "guides" out there were basically rubbish. I have no shame in admitting that I am a n00b, but it took me ages to figure out that when it came to this, all the guides / FAQs / Wikis people always refer to were basically useless. Simply put, irrespective of hardware, software and who should have done what, the documentation needs to be updated because "it needs a lot of memory" is just a lie,

**Comment by garybuhrmaster** [comment]
"the documentation needs to be updated"

And the project looks forward to your contribution.  Please go to the wiki and request a login to update the wiki, and/or to submit pull requests to the project to improve the documentation.

**Comment by honir** [comment]
Jerry V did a lot of work on a replacement IMDb.pm using SQLite to avoid the memory issues inherent in the current flat-file design,
https://metacpan.org/release/IMDB-Local 
https://github.com/JerryVeldhuis/IMDB-Local
but that has been overtaken by events now that the IMDb dataset is no longer being maintained by Amazon (owners of IMDb).

The latest data extract files (from 22 Dec 2017) are [still available](ftp://ftp.fu-berlin.de/pub/misc/movies/database/frozendata/) (at the moment) but won't be updated, and may disappear if Amazon choose to renege on the original licensing agreement from 1998 (when Amazon agreed to make dumps of the database available for free download).

So I suggest there's no point in doing any work on the old plain-text data files: effort would be better directed at a new database based on TMDb or OMDb.  (see #17)

**Comment by honir** [comment]
I've made some tweaks to [IMDB.pm](https://github.com/XMLTV/xmltv/blob/master/lib/IMDB.pm) which has reduced the memory usage during the database build from 2.1 GB to 740 MB. 

Better, but still too much. I'm working on a revised version that will drop that right down.

Aside: This change also fixes a latent bug where some tv-series are sometimes missing their data (or have data from an individual episode attached to the series as a whole).

**Comment by rmeden** [comment]
excellent.. going under 2G will allow it to work on 32 bit systems.

(sadly, I still can't get builds working for xmltv.exe!)

**Comment by knowledgejunkie** [comment]
@honir Thanks for the work on this.

Now that I've updated the CentOS 8 dockerfile, Travis reports that the testsuite for tv_imdb is reporting a failure:

`PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t

t/test_dst.t ......... ok

t/test_filters.t ..... running small test suite, use t/test_filters.t --full for the whole lot

t/test_filters.t ..... ok

t/test_icon.t ........ ok

t/test_library.t ..... ok

t/test_tv_augment.t .. ok

t/test_tv_imdb.t ..... 9/14 t/data-tv_imdb/Show1.xml failed to match expected ('    <category lang="en">TV Series</category>' != '  </programme>')

t/test_tv_imdb.t ..... Failed 1/14 subtests 

t/test_tv_split.t .... 3/21 assuming default UTF-8 encoding for output

t/test_tv_split.t .... 12/21 assuming default UTF-8 encoding for output

assuming default UTF-8 encoding for output

t/test_tv_split.t .... ok

Test Summary Report

-------------------

t/test_tv_imdb.t   (Wstat: 0 Tests: 15 Failed: 2)

  Failed tests:  14, 14

  Parse errors: Tests out of sequence.  Found (14) but expected (15)

                Bad plan.  You planned 14 tests but ran 15.

Files=7, Tests=166, 42 wallclock secs ( 0.07 usr  0.01 sys + 38.08 cusr  3.52 csys = 41.68 CPU)

Result: FAIL

Failed 1/7 test programs. 2/166 subtests failed.

make: *** [Makefile:1772: test_dynamic] Error 255`

**Comment by honir** [comment]
Oops, sorry @knowledgejunkie.  I've fixed the test file to reflect the changes, and testsuite should be happy now

**Comment by knowledgejunkie** [comment]
Great stuff @honir! Starting the new year in green!

**Comment by honir** [comment]
I've reworked the database build side of tv_imdb and committed the changes.

A few noteworthy changes:

- further reduced memory usage during build stages (565 MB required)

- a new option --filesort which will reduce memory further by using the operating system rather than Perl to sort the incoming data (170 MB required). 

- the --movies-only option now added to the database build to remove tv-series from the database build. This further reduces (slightly) the memory requirement, and also the size of the final database. (The augmenting xml listings process should also be a bit quicker.)

- several small bug fixes (missing/incorrect data in the output files)

These changes reduce the memory requirement of tv_imdb from over 2.5 GB down to a mere 170 MB.
.

By default tv_imdb will still use main memory for most of the build but the memory requirement has been reduced to 565 MB. This should be satisfactory for most people.

If you want to save more memory then you need to use the --filesort option. This will chop the memory down to 170 MB, but at the expense of a slightly longer build time. I say "slightly" but... there are actually two options within --filesort. 

The build will try to use the operating system's "sort" command. (At time of writing this has been tested only on Linux, and is currently untested on Windows or Cygwin, and not available on MacOS.) This will add a couple of minutes to the build time. 

An alternative is to use Perl's File::Sort package (assuming you have it installed), but this is very slow (it takes over 45 minutes to sort a file which the O/S sorts in 20 seconds!) and will add several hours to the total build time. But if you want to use this option then specify "--filesort --nosystemsort" as options.

Summary:
--filesort = uses operating system for sorting (170 MB)
--filesort --nosystemsort = uses File::Sort (230MB)
(neither) = uses internal Perl sort (565 MB)
.

Since memory usage in tv_imdb is no longer a problem I'm closing this issue now ;-)

**Comment by knowledgejunkie** [comment]
@honir Just wanted to thank you for your work on this issue - I hope it has noticeable benefits for all users of tv_imdb

**Comment by honir** [comment]
@knowledgejunkie  NP. It took longer than I intended, but once I'd started I couldn't quit ;-)
Hopefully it will make tv_imdb more usable.
