### ISSUE TITLE
tv_grab_uk_tvguide can't get channel list (--configure is broken)

### ISSUE THREAD

**Issue by qdacsvx** [XMLTV/xmltv#64]
The source website recently updated, moving some channels to different id numbers.

$ tv_grab_uk_tvguide --configure
Fetching channels:   0% [                                                                            ]Can't call method "look_down" on an undefined value at /usr/bin/tv_grab_uk_tvguide line 758.

I already have a previously configured grabber. Same error for --list-channels.

XMLTV Version?
--------------
$ tv_grab_uk_tvguide --version
XMLTV module version 0.6.1
This is tv_grab_uk_tvguide version 1.21

XMLTV Component?
----------------
…
tv_grab_uk_tvguide

What happened?
--------------
…

Can't list channels using --list-channels or --configure. An error message is printed.

What did you expect to happen?
------------------------------
…
(Configure works.)
List channels.

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
…
"Can't call method "look_down" on an undefined value at /usr/bin/tv_grab_uk_tvguide line 758."

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
…
Issue is consistent.

What other software are you using?
----------------------------------
**Operating System:** …
Xubuntu

**Perl Version:** …
$ perl --version

This is perl 5, version 26, subversion 1 (v5.26.1)

**Comment by honir** [comment]
Thanks for the report. Fixed here: https://github.com/XMLTV/xmltv/blob/master/grab/uk_tvguide/tv_grab_uk_tvguide
