### ISSUE TITLE
tv_grab_pt_meo empty string

### ISSUE THREAD

**Issue by diogodsoliveira** [XMLTV/xmltv#67]
XMLTV Version?
xmltv-0.5.70

What happened?
after execute:
.\xmltv.exe tv_grab_pt_meo --configure
with success

when execute:
.\xmltv.exe tv_grab_pt_meo --days 7 --output epg.xml --debug

I get the following error:
Empty String at /<C:\Users\doliv\Desktop\xmltv-0.5.70-win32\xmltv.exe>grab/pt_meo/tv_grab_pt_meo line 160.

----------------------------------
**Operating System:** 
Windows 10

**Comment by honir** [comment]
When did it last work for you?
Where (which country) are you accessing it from?

.
It's possible they have now implemented their registration requirement
https://store.services.sapo.pt/en/cat/catalog/other/meo-epg/coverage

**Comment by diogodsoliveira** [comment]
Thanks for your reply Honir.
I'm accessing from Portugal.
Already working again, I didn't need to do anything.
