### ISSUE TITLE
tv_grab_se_swedb: upstream source data files are empty

### ISSUE THREAD

**Issue by knowledgejunkie** [XMLTV/xmltv#71]
XMLTV Version?
--------------

Latest git

XMLTV Component?
----------------

tv_grab_se_swedb

What happened?
--------------

Upstream source data (channel map and listings) are being regenerated daily but are empty.

Not clear if this means the service is being wound down in favour of the new tv_grab_eu_smltvse replacement.

What did you expect to happen?
------------------------------

Normal listings retrieval.

Did you see any warnings/errors?
--------------------------------

$ less t_se_swedb_1.log
Failed to fetch http://xmltv.tvsajten.com/xmltv/channels.xml.gz at /usr/bin/tv_grab_se_swedb line 346.

**Comment by jnylen** [comment]
It says on the main page tvsajten.com that the projects are paused due to personal issues but will be resumed later.

**Comment by knowledgejunkie** [comment]
Thank you for the update - we'll disable it for now and enable it again once the site is operational again.

**Comment by jnylen** [comment]
I'll ping the owner.

@geijer

**Comment by geijer** [comment]
Hi, unfortunately due to no demand, I put the project "on hold" and prioritized other personal and professional projects.
You are the second contact I have had this year regarding tvsajten.com at all, unfortunately I do lack time and motivation to fix it :(

Maybe I should point http://xmltv.tvsajten.com/xmltv/channels.xml.gz to your solution @jnylen ?

**Comment by jnylen** [comment]
@geijer,

Go ahead and point it ;)

I thank you for the time you've spent so far ;)

**Comment by geijer** [comment]
How do I do that best? Mirror your http://xmltv.xmltv.se/channels-Sweden.xml.gz as  http://xmltv.tvsajten.com/xmltv/channels.xml.gz ?

**Comment by jnylen** [comment]
Hi,
Or you can point xmltv.tvsajten.com to ftp.xmltv.se and I'll put a custom folder structure up for your users.

Do what makes it easier for you. 👍

**Comment by jnylen** [comment]
I guess we can close this then as the source kinda closed down?

Feel free to open it if it changes ;)
