### ISSUE TITLE
tv_grab_ch_search: most channels are empty

### ISSUE THREAD

**Issue by wisiz** [XMLTV/xmltv#73]
XMLTV Version?
--------------
v0.6.1

XMLTV Component?
----------------
tv_grab_ch_search

What happened?
--------------
For several channels no data is collected, e.g. ntv.search.ch

Only the following channels give results:
k1ch.search.ch
orf1.search.ch
orf2.search.ch
pro7ch.search.ch
rtl2.search.ch
rtlch.search.ch
sat1ch.search.ch
sf1.search.ch
sf2.search.ch
voxch.search.ch
zdf.search.ch

What did you expect to happen?
------------------------------
Data for all channels

Did you see any warnings/errors?
--------------------------------
No

What steps are needed to reproduce this issue?
----------------------------------------------
Run grabber

Any other information?
----------------------

What other software are you using?
----------------------------------
Ubuntu 18.10

**Perl Version:**
v5.26.1

**Comment by mkeller** [comment]
Started to fail a few weeks ago.

It looks like the channel selection is not being used at all, and it just fetches search.ch's default channels. Maybe that set has been reduced for clients that don't have any cookies set?

The current tv_grab_ch_search fetches URLs like this:
https://tv.search.ch/?time=2019-10-26+8.00

I guess the quickest fix would be to simulate a user that modifies the channel list and gets a new cookie.

IMO, a better strategy would be to directly grab urls like https://tv.search.ch/einsfestival .
But that probably requires a new parser.

**Comment by mkeller** [comment]
> I guess the quickest fix would be to simulate a user that modifies the channel list and gets a new cookie.

There was already code that partly implemented that, but it didn't work any more. I've completed the handling of cookies and adapted the grabber to the current website.

**Comment by wisiz** [comment]
Thanks for the fix, receiving all data again.

**Comment by markus-ksg** [comment]
👍 I also got a direct mail from someone who said he's happy with my fix installed on top of xmltv 0.5.70-1 for Ubuntu 18.04 LTS.

**Comment by mkeller** [comment]
👍 I also got a direct mail from someone who said he's happy with my fix installed on top of xmltv 0.5.70-1 for Ubuntu 18.04 LTS.

**Comment by crestAT** [comment]
Thanx for the fix, recognized missing data for ORFIII, with your fix it's working again!
