### ISSUE TITLE
Actors with icons?

### ISSUE THREAD

**Issue by bam80** [XMLTV/xmltv#79]
Am I understand right that icons can be assigned to actors in following way?:
```xml
<actor>
  <value>Peter Bergman</value>
  <icon src="http://metadata_site.com/image_of_Peter_Bergman.gif" />
</actor>

**Comment by garybuhrmaster** [comment]
As I recall, the DTD does not allow credits to have an icon attribute/element (the only additional attribute is for actors, and is for the role being played).

**Comment by bam80** [comment]
Seems you are right, thanks.

Yet another question - is `episode-num` element can be used to refer to a movie in common metadatabases, as shown here:
https://github.com/XMLTV/xmltv/blob/6d1a36b7cde8f692425f6deac9d7d36447b1c4ab/xmltv.dtd#L409

Using that, one probably could use these site APIs to pull lacking arts, e.g - the actor icons?

**Comment by garybuhrmaster** [comment]
episode-num is used by some grabbers to pass along those references that may be able to be used to acquire additional information.  Note that not all upstream sources likely have such additional information available (at all, or for all programmes).  And some downstream applications will choose to do their own metadata lookups with the program titles/descriptions provided, regardless of whether the grabber passes its references along.

**Comment by bam80** [comment]
Ok thanks. Just thinking how it would be better achieved in Kodi PVR skins like this:
https://github.com/louisbraun/skin.unfussy/blob/master/README.md

**Comment by garybuhrmaster** [comment]
I believe the xmltv questions have been resolved.  Closing issue.

**Comment by bam80** [comment]
Yes, thanks. Just one more thought - why not just allow icon attribute for actors? As you see, real PVR apps use it, so for now they have to overcome this XMLTV shortcoming.. Maybe this is indicator to expand the spec?
