### ISSUE TITLE
tv_validate_file reports missing tz when it is optional

### ISSUE THREAD

**Issue by higuita** [XMLTV/xmltv#81]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
0.5.67

XMLTV Component?
----------------
tv_validate_file

What happened?
--------------
When updatingand testing a update pt_vodafone grabber, i'm using dates with utc, so no  timezone defined. Validating the file i get:

$ tv_validate_file /tmp/list.xmltv
Use of uninitialized value $tz in hash element at /usr/share/perl5/vendor_perl/XMLTV/ValidateFile.pm line 276.
Use of uninitialized value $tz in pattern match (m//) at /usr/share/perl5/vendor_perl/XMLTV/ValidateFile.pm line 283.

No timezone specified
Line 861 Invalid start-time '20200101030000'
2 errors found.

example programme:

```
  <programme start="20200101210000" stop="20200101214500" channel="ngc.tv.vodafone.pt">
    <title lang="pt">O Incrível Dr. Pol</title>
    <sub-title lang="pt">Todos em Apuros</sub-title>
    <desc lang="pt">Uma cabra Boer fica presa numa cerca de arame, o que causa uma lesão na perna que a coloca risco de vida, enquanto uma Weimaraner se encontra entre a espada e a parede. Mas serão todas as feridas auto-infligidas?</desc>
    <category lang="pt">Documentários</category>
    <length units="minutes">45</length>
    <icon src="http://web.ottimg.vodafone.pt/iptvimageserver/Get/36_121176033/4_3/684/513" />
    <episode-num system="onscreen">T9 Ep6</episode-num>
  </programme>
```

What did you expect to happen?
------------------------------
timezone is marked as optional, so should not return error. So it should return a Valid format.
If i add a +0000 timezone, it validates fine

What other software are you using?
----------------------------------
**Operating System:** Slackware linux 64bit

**Perl Version:** v5.30.1

**Comment by knowledgejunkie** [comment]
The XMLTV DTD states that a timezone is optional, and defaults to UTC if omitted. The date/time validation in ValidateFile is much more rigid.

lib/ValidateFile.pm not only requires a timezone to be present to validate successfully, but also that it must have the format [+-]\d{4}.

We could relax the validation to match the DTD which is the agreed format for XMLTV, but should discuss whether we might tighten these requirements in the future. Let's discuss this on xmltv-devel.

**Comment by higuita** [comment]
Ok, thanks, not a critical issue, after all this is a support/developer tool :)

I also tried with a timezone GMT (start="20200101210000 GMT" ) and it also fails (as you say, it waiting for numbers only). If rules are updated, do not forget to also remove the BST example from the DTD
