### ISSUE TITLE
standalone exe: tv_grab_huro stopped working: error 500 can't connect to port.hu:443

### ISSUE THREAD

**Issue by BuXY** [XMLTV/xmltv#84]
XMLTV Version?
--------------
0.6.1
tv_grab_huro module version: 0.6.1

XMLTV Component?
----------------
Standalone compiled xmltv.exe binary
tv_grab_huro

What happened?
--------------
I tried to run either grabbing or configuring, but the module could not connect to the programme provider. My console output:
```
d:\xmltv>xmltv tv_grab_huro -days 9 --output xmltv.xml
Timezone is +0100
using config filename ./.xmltv/tv_grab_huro.conf
getting list of channels: could not fetch http://www.port.hu/tvapi/init, error: 500 Can't connect to port.hu:443, aborting
```
It was working fine until quite a few weeks ago (maybe around January-February 2020).

What did you expect to happen?
------------------------------
Start downloading channels and programmes without error 500. Like:
```
getting list of channels: ##################################################
getting channel details : ##################################################
```

Did you see any warnings/errors?
--------------------------------
`getting list of channels: could not fetch http://www.port.hu/tvapi/init, error: 500 Can't connect to port.hu:443, aborting`

What steps are needed to reproduce this issue?
----------------------------------------------
1. `xmltv tv_grab_huro -days 9 --output xmltv.xml`

Alternatively:
1. `del .xmltv\*.*`
2. `xmltv --configure`
3. `Grab listings for which country? [Hungary (default=Hungary)]` (just press enter)

Any other information?
----------------------
- Binary downloaded from http://xmltv.org/alpha/xmltv.exe on 1st March, 2020.
- xmltv.exe running on Windows refuses to connect.
- An older xmltv.exe version 0.5.69 running on Windows refuses to connect.
- Internal tv_grab_huro plugin 0.5.69 in tvheadend 4.2.6-92~g06c206c3b running on Linux 4.18.0-0.bpo.1-marvell (my NAS) works perfectly. (I had to run --configure manually in a weird way, but it works.)
- Firefox 73.0.1 64-bit on Windows opens https://port.hu/tvapi/init correctly.

What other software are you using?
----------------------------------
**Operating System:** Windows 7 Home Premium 64-bit

**Perl Version:** I cannot determine that from the standalone Windows binary. (My NAS Linux has Perl 5.24.1 installed, but it is out of question.)

**Comment by d3cadent** [comment]
I can confirm the same on my own system.

Perl version: ActiveState Perl v5.10.0
