### ISSUE TITLE
tv_grab_uk_tvguide can't parse channel 1529, 1530

### ISSUE THREAD

**Issue by qdacsvx** [XMLTV/xmltv#87]
XMLTV Version?
--------------
git head,
$ tv_grab_uk_tvguide --version
XMLTV module version 0.6.1
This is tv_grab_uk_tvguide version 0.6.1 

XMLTV Component?
----------------
…

What happened?
--------------
Grabber reports validation failure.

What did you expect to happen?
------------------------------
Grabber downloads channels.

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
…
Validation failed for type named Num declared in package Specio::Library::Builtins (/usr/share/perl5/Specio/Library/Builtins.pm) at line 139 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Num declared in package Specio::Library::Builtins (/usr/share/perl5/Specio/Library/Builtins.pm) at line 139 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x55f98862eb70)', 'value', undef) called at (eval 239) line 88
DateTime::_check_from_epoch_params('epoch', undef) called at /usr/lib/x86_64-linux-gnu/perl5/5.28/DateTime.pm line 481
DateTime::from_epoch('DateTime', 'epoch', undef) called at /usr/local/bin/tv_grab_uk_tvguide line 385
main::fetch_listings at /usr/local/bin/tv_grab_uk_tvguide line 128

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. …
install and configure grabber. Configure grabber to include channel 1529, 1530.
2. …
$tv_grab_uk_tvguide  --config-file x.conf
3. …
$cat x.conf
cachedir=/tmp/cache
channel=1529
channel=1530

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
…
Consistent for several days since these channels were added to the source website.

What other software are you using?
----------------------------------
**Operating System:** …
Linux debian 4.19.0-6.amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)
**Perl Version:** …
perl 5, version 28, subversion 1 (v5.28.1)

**Comment by honir** [comment]
Thanks for the report, and for the detailed info.  Fixed.
