### ISSUE TITLE
tv_grab_uk_tvguide can't configure

### ISSUE THREAD

**Issue by qdacsvx** [XMLTV/xmltv#90]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
$ tv_grab_uk_tvguide --version
XMLTV module version 0.6.1
This is tv_grab_uk_tvguide version 0.6.1

XMLTV Component?
----------------
tv_grab_uk_tvguide

What happened?
--------------
Error during --configure.

What did you expect to happen?
------------------------------
Configure with no errors.

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
Can't call method "look down" on an undefined value at /usr/bin/tv_grab_uk_tvguide line 758.

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1.  $tv_grab_uk_tvguide --configure --debug
tv_grab_uk_tvguide uses a cache...
Fetching channels:   0% [
Can't call method "look down" on an undefined value at /usr/bin/tv_grab_uk_tvguide line 758.

Any other information?
----------------------
Source website recently cleaned up, deleting ?all channels above 1324. ?All deleted channels have an alias channel of 1324 or less.

What other software are you using?
----------------------------------
**Operating System:** …
Linux 4.19.114-0419114-generic #202004021037 SMP Thu Apr 2 14:42:12 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Perl Version:** …
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

**Comment by honir** [comment]
I can't relate that line number to the current code listing (it doesn't seem right).

I can't replicate this issue. You could try clearing out the xmltv cache. 

Alternatively these type of errors can indicate a failure to retrieve the target web page
- try rerunning the config to check for a transient error
- check your dns is resolving for www.tvguide.co.uk and my.tvguide.co.uk and you can retrieve the website:
````
wget  https://www.tvguide.co.uk/channellisting.asp?ch=74&cTime=
````

**Comment by qdacsvx** [comment]
Agreed it's currently working. I think the source server updated. (I wanted --list-channels; I already have a configured grabber. I'm afraid --configure was broken for weeks before I noticed.) There was a previous error
https://github.com/XMLTV/xmltv/issues/64
 which lasted long enough for a patch. The server sometimes moves channels around so there's no guarantee that a given channel is available for --configure to download to scrape the channels list. The grabber could try multiple channels or sample randomly (channel ids are just numbers for this grabber).

**Comment by honir** [comment]
It has only been necessary to change the channel id used for fetching the channels list once in seven years. 

If the channel id for BBC1 (the channel used to fetch the channels list) ever changes then it's trivial to change the id to another one.

**Comment by hjaltioj** [comment]
I get this file when i grab: 
XMLTV::Supplement: Failed to read from /home/user/.xmltv/supplement/tv_grab_uk_tvguide/tv_grab_uk_tvguide.map.conf.

??

**Comment by honir** [comment]
Please don't hijack other threads.

Check that file exists, is readable, and that it contains valid data, and if so then open a new issue.
