### ISSUE TITLE
tv_grab_na_dtv: add zipcode as command argument?

### ISSUE THREAD

**Issue by kevev** [XMLTV/xmltv#95]
Is there any way to have tv_grab_na_dtv accept zipcode as command argument?

ex: tv_grab_na_dtv -z 10229

**Comment by rmeden** [comment]
Apps are allowed to add non-standard command line switches,  but is 
there a reason not to follow the normal --configure process?  It's 
normally only done once.

**Comment by kevev** [comment]
Thank You for the reply. I am wanting parse a zipcode list. I have tried creating an expect script to do this. But having issues. Now that I think of it, I don't know how command arguments could handle saying yes/no to channel selection.

**Comment by rmeden** [comment]
On 5/28/2020 1:01 PM, kevev wrote:
>
> Thank You for the reply. I am wanting parse a zipcode list. I have 
> tried creating an expect script to do this. But having issues. Now 
> that I think of it, I don't know how command arguments could handle 
> saying yes/no to channel selection.
>
Hmmm trying to get guide listings just to parse a zipcode doesn't seem 
like a fair load on the directtv servers.  Doesn't the USPS offer a 
zipcode list?  At least I think they provide an address validation API.

**Comment by kevev** [comment]
I am only doing this for 3 cities in my state.

**Comment by rmeden** [comment]
closing.. tv_grab_na_dtv removed due to site changes
