### ISSUE TITLE
TV Guide Fatal Error

### ISSUE THREAD

**Issue by whiteshadow10189** [XMLTV/xmltv#98]
XMLTV Version?
--------------
0.5.70

XMLTV Component?
----------------
…

What happened?
--------------
Whenever I open the TVG app and select XMLTV.EXE as the EXE Location, I get this error 

![error message](https://user-images.githubusercontent.com/66579649/83986554-d3ffb200-a902-11ea-8a4b-bf8502f88fcf.PNG)

What did you expect to happen?
------------------------------
No Errors

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)
…

What steps are needed to reproduce this issue?
----------------------------------------------
(Please provide the full commands you are running)
1. …
2. …
3. …

Any other information?
----------------------
(For example, is this a new or intermittent issue?)
…

What other software are you using?
----------------------------------
**Operating System:** … Windows 10

**Perl Version:** …

**Comment by pmhahn** [comment]
Please complain to "TVG" - we are not responsible for them providing our software (if it is our code at all). At least provide an URL of their homepage as "TVG" is too generic to search for.
